-- 287-card curated batch added 2026-10-02 from a user-curated list of 300
-- divisive/shareable dilemmas (originally grouped by informal vibe categories —
-- Relationships, Dating, Friends, Work, Money, Family & in-laws, Morally gray,
-- Petty/funny — remapped here to the 5 real posts.category values since those
-- groupings aren't DB categories). 13 of the original 300 were not inserted:
--   8 removed as exact/semantic duplicates of existing approved content or of
--     each other (see git history / conversation record for the specific list)
--   5 held back because they triggered the live moderation pipeline on what is
--     almost certainly harmless wording (e.g. a capitalized brand-name-as-verb
--     like "Googled"/"Venmo-requested" being misread as a proper name, and the
--     word "hurt" immediately before a pronoun matching an imperative-violence
--     check even in a purely descriptive, non-threatening sentence) — NOT
--     inserted, and the moderation code itself was deliberately left unchanged.
--
-- Insertion order below is pre-shuffled (greedy category-balanced interleave,
-- never two consecutive cards from the same category) purely so this file
-- itself doesn't read as thematic blocks — note this has no effect on live
-- serving order: get_feed()'s seed lane already does ORDER BY random() on
-- every fetch regardless of row insertion order (see get_feed() in
-- 20260809000003_get_feed.sql), which was intentionally left unchanged here.
-- Every line was run through the live submit-post moderation function before
-- insertion, since a direct seed insert bypasses that Edge Function entirely.

insert into posts (text, category, safety_flag, status, source) values
  ('My partner wants to wait until marriage before telling their family about me.', 'relationship', false, 'approved', 'seed'),
  ('My friend invited everyone in our group on vacation except one person.', 'friendship', false, 'approved', 'seed'),
  ('My partner thinks their parents should be able to visit without much notice.', 'relationship', false, 'approved', 'seed'),
  ('My friend got engaged and asked me not to get engaged until after their wedding.', 'friendship', false, 'approved', 'seed'),
  ('My partner wants to financially support their parents every month after we marry.', 'relationship', false, 'approved', 'seed'),
  ('My friend wants to approve the person I''m dating before things get serious.', 'friendship', false, 'approved', 'seed'),
  ('My partner refuses to tell me how much debt they have until we''re engaged.', 'relationship', false, 'approved', 'seed'),
  ('My friend says "I''m on my way" while they''re still getting dressed.', 'friendship', false, 'approved', 'seed'),
  ('Someone I''m dating still talks to their ex''s parents regularly.', 'relationship', false, 'approved', 'seed'),
  ('My friend screenshots our conversations and sends them to their partner.', 'friendship', false, 'approved', 'seed'),
  ('My partner thinks vacations with friends should sometimes exclude spouses.', 'relationship', false, 'approved', 'seed'),
  ('My friend gave me a gift I hated, so I returned it and bought something else.', 'friendship', false, 'approved', 'seed'),
  ('My partner would rather cancel our vacation than leave our dog with someone else.', 'relationship', false, 'approved', 'seed'),
  ('My friend earns much more than me but always chooses restaurants outside my budget.', 'friendship', false, 'approved', 'seed'),
  ('My partner doesn''t believe couples should know each other''s exact salaries until engagement.', 'relationship', false, 'approved', 'seed'),
  ('My friend wants everyone to stop talking to their ex after the breakup.', 'friendship', false, 'approved', 'seed'),
  ('My partner always steals my fries after saying they don''t want any, so I started ordering extra without telling them.', 'relationship', false, 'approved', 'seed'),
  ('My friend copies almost every new thing I buy.', 'friendship', false, 'approved', 'seed'),
  ('My partner spends heavily on hobbies but complains when I buy expensive clothes.', 'relationship', false, 'approved', 'seed'),
  ('My friend arrives late but somehow gets annoyed when other people are late.', 'friendship', false, 'approved', 'seed'),
  ('My partner wants a prenup that keeps everything we individually earn during marriage separate.', 'relationship', false, 'approved', 'seed'),
  ('My friend always tells me the truth about my decisions even when I didn''t ask.', 'friendship', false, 'approved', 'seed'),
  ('My partner says engagement rings are a waste of money and doesn''t want to buy one.', 'relationship', false, 'approved', 'seed'),
  ('My friend told me they don''t like my partner and refuses to pretend otherwise.', 'friendship', false, 'approved', 'seed'),
  ('My partner wants their mother in the delivery room someday.', 'relationship', false, 'approved', 'seed'),
  ('My friend constantly complains about their partner but gets angry when I criticize them.', 'friendship', false, 'approved', 'seed'),
  ('My partner wants us to move closer to their parents before having children.', 'relationship', false, 'approved', 'seed'),
  ('My friend asked whether I like their engagement ring. I don''t. Should I be honest?', 'friendship', false, 'approved', 'seed'),
  ('My partner wants to keep our relationship private until we''re engaged.', 'relationship', false, 'approved', 'seed'),
  ('My friend always chooses expensive restaurants, so I started declining without explaining that money is the reason.', 'friendship', false, 'approved', 'seed'),
  ('My partner thinks lending money to friends should be a joint decision after marriage.', 'relationship', false, 'approved', 'seed'),
  ('My friend constantly cancels plans, so I stopped inviting them without explaining why.', 'friendship', false, 'approved', 'seed'),
  ('My partner doesn''t want our future children posted anywhere online, even by family.', 'relationship', false, 'approved', 'seed'),
  ('My friend wants to split appetizers evenly even though they ate most of them.', 'friendship', false, 'approved', 'seed'),
  ('My partner said they didn''t want gifts, so I actually bought nothing. Now they''re disappointed.', 'relationship', false, 'approved', 'seed'),
  ('My friend wants everyone to spend thousands on their destination wedding.', 'friendship', false, 'approved', 'seed'),
  ('My date keeps their phone face-down whenever we''re together.', 'relationship', false, 'approved', 'seed'),
  ('My friend copied my business idea, so I stopped telling them anything about my plans.', 'friendship', false, 'approved', 'seed'),
  ('My partner goes through my phone but won''t let me touch theirs.', 'relationship', false, 'approved', 'seed'),
  ('My friend keeps borrowing my clothes and returning them months later.', 'friendship', false, 'approved', 'seed'),
  ('My partner believes some flirting is acceptable as long as there''s no intention to cheat.', 'relationship', false, 'approved', 'seed'),
  ('My friend wants to bring their partner to every girls'' trip.', 'friendship', false, 'approved', 'seed'),
  ('My partner says their parents should never have to stay in a hotel when visiting us.', 'relationship', false, 'approved', 'seed'),
  ('My friend thinks close friends should share their live locations.', 'friendship', false, 'approved', 'seed'),
  ('My partner still shares their location with their ex because they''re "still close."', 'relationship', false, 'approved', 'seed'),
  ('My friend gets upset when I hang out with our mutual friends without inviting them.', 'friendship', false, 'approved', 'seed'),
  ('My partner deleted old messages with their ex because they knew I''d overthink them.', 'relationship', false, 'approved', 'seed'),
  ('I saw my friend''s partner on a dating app, but the profile could be old. Should I tell my friend immediately?', 'friendship', false, 'approved', 'seed'),
  ('My partner says having separate bedrooms would make our relationship healthier.', 'relationship', false, 'approved', 'seed'),
  ('My friend invited me to a trip and later told me I''d be sleeping on the couch while couples get rooms.', 'friendship', false, 'approved', 'seed'),
  ('My partner wants to spend every holiday with their family because "that''s how we''ve always done it."', 'relationship', false, 'approved', 'seed'),
  ('My best friend expects to be my maid of honor because we''ve known each other longest.', 'friendship', false, 'approved', 'seed'),
  ('My partner pauses movies every ten minutes to explain theories.', 'relationship', false, 'approved', 'seed'),
  ('My friend got upset because I didn''t post anything for their birthday.', 'friendship', false, 'approved', 'seed'),
  ('My partner wants their parents to stay with us for several months every year.', 'relationship', false, 'approved', 'seed'),
  ('My friend ignored me for months while dating someone, so now I''m keeping some distance after their breakup.', 'friendship', false, 'approved', 'seed'),
  ('Someone I''m dating wants to see me every day after only two weeks.', 'relationship', false, 'approved', 'seed'),
  ('My roommate leaves exactly one square of toilet paper so they don''t have to replace the roll.', 'friendship', false, 'approved', 'seed'),
  ('My date brought up marriage and kids on the first date.', 'relationship', false, 'approved', 'seed'),
  ('My friend didn''t invite my partner to their wedding even though we''ve been together for years.', 'friendship', false, 'approved', 'seed'),
  ('My partner sets 12 alarms every morning and sleeps through 11 of them.', 'relationship', false, 'approved', 'seed'),
  ('My roommate eats my food, so I started keeping the good snacks in my bedroom.', 'friendship', false, 'approved', 'seed'),
  ('My date asked to split a $20 bill after inviting me out.', 'relationship', false, 'approved', 'seed'),
  ('My friend vents about the same problem every week, so I told them I don''t want to discuss it anymore.', 'friendship', false, 'approved', 'seed'),
  ('My partner says cheating once shouldn''t automatically end a long relationship.', 'relationship', false, 'approved', 'seed'),
  ('My friend keeps making jokes about embarrassing things I did years ago.', 'friendship', false, 'approved', 'seed'),
  ('My partner thinks liking thirst traps isn''t disrespectful because "it''s just Instagram."', 'relationship', false, 'approved', 'seed'),
  ('My friend expects the highest earner in the group to pay more on vacations.', 'friendship', false, 'approved', 'seed'),
  ('Someone I''m dating says they''re not ready for a relationship but wants exclusivity.', 'relationship', false, 'approved', 'seed'),
  ('My friend announced their engagement during another friend''s birthday dinner.', 'friendship', false, 'approved', 'seed'),
  ('My partner tells their best friend details about every argument we have.', 'relationship', false, 'approved', 'seed'),
  ('My friend started dating someone I used to have feelings for.', 'friendship', false, 'approved', 'seed'),
  ('My partner says we should never go to bed angry, even if that means arguing until 3 a.m.', 'relationship', false, 'approved', 'seed'),
  ('My manager gave me more work because I''m "the reliable one."', 'career', false, 'approved', 'seed'),
  ('My partner wants us to have one joint account but also separate personal accounts.', 'relationship', false, 'approved', 'seed'),
  ('My coworker always asks for help but never helps me, so I started saying I''m too busy.', 'career', false, 'approved', 'seed'),
  ('My partner wants me to unfollow someone I used to date casually.', 'relationship', false, 'approved', 'seed'),
  ('My friend expects us to split restaurant bills evenly even when they order much more.', 'friendship', false, 'approved', 'seed'),
  ('My partner doesn''t want me discussing our fights with anyone, including my closest friends.', 'relationship', false, 'approved', 'seed'),
  ('My coworker refuses to train new hires because "that''s management''s job."', 'career', false, 'approved', 'seed'),
  ('My partner thinks debt from before marriage should stay entirely separate.', 'relationship', false, 'approved', 'seed'),
  ('My coworker keeps interrupting me, so I started interrupting them back.', 'career', false, 'approved', 'seed'),
  ('My partner has a secret personal savings account "just in case."', 'relationship', false, 'approved', 'seed'),
  ('My friend asked me to lend them money while they still owe me from last time.', 'friendship', false, 'approved', 'seed'),
  ('My partner needs subtitles on even when the movie is in our language.', 'relationship', false, 'approved', 'seed'),
  ('My coworker keeps correcting people''s grammar in team chats.', 'career', false, 'approved', 'seed'),
  ('My partner wants a separate emergency fund that only they can access.', 'relationship', false, 'approved', 'seed'),
  ('My manager invited the whole team to their wedding.', 'career', false, 'approved', 'seed'),
  ('My partner wants to keep the inheritance they receive completely separate after marriage.', 'relationship', false, 'approved', 'seed'),
  ('My friend expects me to pay more on trips because I earn more.', 'friendship', false, 'approved', 'seed'),
  ('My partner forgot our anniversary, so I decided not to remind them and waited to see when they''d notice.', 'relationship', false, 'approved', 'seed'),
  ('My roommate steals my phone charger and returns it at 3%.', 'friendship', false, 'approved', 'seed'),
  ('My partner leaves one sip in every drink instead of finishing it.', 'relationship', false, 'approved', 'seed'),
  ('I know my coworker is interviewing elsewhere and our manager directly asked me about it. Should I lie?', 'career', false, 'approved', 'seed'),
  ('My partner doesn''t believe couples need to celebrate anniversaries.', 'relationship', false, 'approved', 'seed'),
  ('My manager expects employees to attend optional happy hours to build relationships.', 'career', false, 'approved', 'seed'),
  ('My partner asks where something is before looking for it.', 'relationship', false, 'approved', 'seed'),
  ('My friend invited me to a destination wedding I can''t afford, so I''m skipping it without sending a gift.', 'friendship', false, 'approved', 'seed'),
  ('My partner says I''m allowed to see their phone, but asking to see it is itself suspicious.', 'relationship', false, 'approved', 'seed'),
  ('My friend says they aren''t hungry and then eats everyone''s food.', 'friendship', false, 'approved', 'seed'),
  ('My partner wants their parents to have unrestricted access to our future children.', 'relationship', false, 'approved', 'seed'),
  ('My sibling announced major personal news at my family celebration without asking.', 'family', false, 'approved', 'seed'),
  ('My partner says some secrets are healthy even in marriage.', 'relationship', false, 'approved', 'seed'),
  ('My parents think helping them financially should come before saving for a house.', 'family', false, 'approved', 'seed'),
  ('My partner can stay friends with an ex, but I can''t.', 'relationship', false, 'approved', 'seed'),
  ('My friend told me about another friend''s secret because they thought I "deserved to know."', 'friendship', false, 'approved', 'seed'),
  ('My partner thinks emotional cheating isn''t real unless something physical happens.', 'relationship', false, 'approved', 'seed'),
  ('My manager messages the team late at night but says replies can wait until morning.', 'career', false, 'approved', 'seed'),
  ('Someone I''m dating refuses to define the relationship but gets jealous when I see other people.', 'relationship', false, 'approved', 'seed'),
  ('My manager told me to be less ambitious because promotions take time.', 'career', false, 'approved', 'seed'),
  ('My partner says flirting is harmless as long as nothing physical happens.', 'relationship', false, 'approved', 'seed'),
  ('My manager expects cameras on for every virtual meeting.', 'career', false, 'approved', 'seed'),
  ('My partner regularly gets drinks alone with an ex and says they''re basically family now.', 'relationship', false, 'approved', 'seed'),
  ('My friend asked everyone to pay for a surprise party they planned without asking us first.', 'friendship', false, 'approved', 'seed'),
  ('My partner reads restaurant menus online hours before we go.', 'relationship', false, 'approved', 'seed'),
  ('My manager told me another employee''s salary while discussing my raise.', 'career', false, 'approved', 'seed'),
  ('My partner has a "work spouse" and thinks I''m insecure for being uncomfortable.', 'relationship', false, 'approved', 'seed'),
  ('My sibling wants me to keep a major family secret from my partner.', 'family', false, 'approved', 'seed'),
  ('My partner wants to know exactly how much money I have saved before engagement.', 'relationship', false, 'approved', 'seed'),
  ('My parents think they should have a say in who I marry because marriage joins families.', 'family', false, 'approved', 'seed'),
  ('My partner thinks wedding costs should be split exactly between both families.', 'relationship', false, 'approved', 'seed'),
  ('My manager expects people to turn Slack notifications on during lunch.', 'career', false, 'approved', 'seed'),
  ('My partner sends me videos while sitting right next to me and waits for me to watch them.', 'relationship', false, 'approved', 'seed'),
  ('My sibling always arrives late, so I told them our reservation was 30 minutes earlier than it actually was.', 'family', false, 'approved', 'seed'),
  ('My partner wants a prenup even though neither of us is rich yet.', 'relationship', false, 'approved', 'seed'),
  ('My friend thinks wedding guests should cover the cost of their own meal through gifts.', 'friendship', false, 'approved', 'seed'),
  ('I discovered my partner looked through my phone, so I changed my password without discussing it.', 'relationship', false, 'approved', 'seed'),
  ('My friend wants me to take their side in an argument even though I think they''re wrong.', 'friendship', false, 'approved', 'seed'),
  ('My partner''s parents expect to have a key to our future house.', 'relationship', false, 'approved', 'seed'),
  ('My coworker has become close friends with our manager outside work.', 'career', false, 'approved', 'seed'),
  ('My partner says I shouldn''t need privacy if I have nothing to hide.', 'relationship', false, 'approved', 'seed'),
  ('My manager scheduled a meeting to discuss something that could''ve been one sentence in Slack.', 'career', false, 'approved', 'seed'),
  ('My partner wants me to stop discussing our relationship with my closest friend.', 'relationship', false, 'approved', 'seed'),
  ('My parents expect me to call them every single day.', 'family', false, 'approved', 'seed'),
  ('My partner tells their parents about our arguments because they need advice.', 'relationship', false, 'approved', 'seed'),
  ('My friend says friendships shouldn''t require "boundaries."', 'friendship', false, 'approved', 'seed'),
  ('My date showed up 30 minutes late without texting but apologized sincerely.', 'relationship', false, 'approved', 'seed'),
  ('My coworker uses "we" when something succeeds and "you" when something fails.', 'career', false, 'approved', 'seed'),
  ('My partner asks what I want to eat and rejects every suggestion.', 'relationship', false, 'approved', 'seed'),
  ('My sibling expects me to forgive their partner because refusing makes family gatherings awkward.', 'family', false, 'approved', 'seed'),
  ('My partner thinks whoever earns more should pay more but shouldn''t get more say over spending.', 'relationship', false, 'approved', 'seed'),
  ('My friend invited me to their birthday dinner and expected everyone else to pay for them.', 'friendship', false, 'approved', 'seed'),
  ('My partner wants their parents to move in with us when they''re older.', 'relationship', false, 'approved', 'seed'),
  ('My coworker asks everyone what they got in their annual bonus.', 'career', false, 'approved', 'seed'),
  ('My partner doesn''t want me traveling alone after we''re married.', 'relationship', false, 'approved', 'seed'),
  ('My sibling thinks being family means we shouldn''t charge each other rent.', 'family', false, 'approved', 'seed'),
  ('My date was rude to the waiter but incredibly nice to me.', 'relationship', false, 'approved', 'seed'),
  ('My roommate leaves empty boxes in the pantry instead of throwing them away.', 'friendship', false, 'approved', 'seed'),
  ('My partner has never introduced me to their coworkers after two years together.', 'relationship', false, 'approved', 'seed'),
  ('My sibling wants me to choose them over my partner during family disagreements.', 'family', false, 'approved', 'seed'),
  ('My date says all of their exes were "crazy."', 'relationship', false, 'approved', 'seed'),
  ('My friend disappears whenever they''re dating someone and returns after every breakup.', 'friendship', false, 'approved', 'seed'),
  ('My partner wants to buy a house together before we''re married.', 'relationship', false, 'approved', 'seed'),
  ('My friend became close friends with someone they know I strongly dislike.', 'friendship', false, 'approved', 'seed'),
  ('My partner said they''d forgive cheating but not lying about money.', 'relationship', false, 'approved', 'seed'),
  ('My coworker regularly takes meetings while walking around outside.', 'career', false, 'approved', 'seed'),
  ('My date follows thousands of attractive strangers online.', 'relationship', false, 'approved', 'seed'),
  ('My coworker asked me my salary and immediately told me theirs.', 'career', false, 'approved', 'seed'),
  ('Someone I''m dating still lives with their ex because the lease isn''t over.', 'relationship', false, 'approved', 'seed'),
  ('My friend regularly cancels our plans when something "better" comes up.', 'friendship', false, 'approved', 'seed'),
  ('My partner thinks it''s fine to have a celebrity crush but not a crush on someone we actually know.', 'relationship', false, 'approved', 'seed'),
  ('My friend thinks you should always choose your closest friend over a romantic partner until marriage.', 'friendship', false, 'approved', 'seed'),
  ('My partner says their family will always come before my friends.', 'relationship', false, 'approved', 'seed'),
  ('My friend says your partner should automatically become your best friend.', 'friendship', false, 'approved', 'seed'),
  ('Someone I''m dating said they wouldn''t marry someone with significant student debt.', 'relationship', false, 'approved', 'seed'),
  ('My manager wants the team to eat lunch together whenever we''re in the office.', 'career', false, 'approved', 'seed'),
  ('My partner said they''d choose their career over our relationship if forced to pick.', 'relationship', false, 'approved', 'seed'),
  ('My parents expect me to ask before making major life decisions.', 'family', false, 'approved', 'seed'),
  ('Someone I''m dating hasn''t told their friends about me after three months.', 'relationship', false, 'approved', 'seed'),
  ('My coworker applied for the same internal role I told them I wanted.', 'career', false, 'approved', 'seed'),
  ('My partner says love isn''t enough to marry someone if their financial habits are bad.', 'relationship', false, 'approved', 'seed'),
  ('My sibling thinks spouses shouldn''t be included in certain family decisions.', 'family', false, 'approved', 'seed'),
  ('My partner leaves chores unfinished, so I stopped finishing them too.', 'relationship', false, 'approved', 'seed'),
  ('My friend wants a child-free wedding but is upset that some parents won''t attend.', 'friendship', false, 'approved', 'seed'),
  ('My partner wants separate vacations with friends every year.', 'relationship', false, 'approved', 'seed'),
  ('My manager told me I''m too valuable in my current role to be promoted yet.', 'career', false, 'approved', 'seed'),
  ('My partner says they''d never combine bank accounts with anyone.', 'relationship', false, 'approved', 'seed'),
  ('My friend skipped my birthday because their partner wasn''t invited.', 'friendship', false, 'approved', 'seed'),
  ('My partner wants our future children named according to their family''s tradition.', 'relationship', false, 'approved', 'seed'),
  ('My sibling wants our parents to divide inheritance equally even though one sibling provides most of their care.', 'family', false, 'approved', 'seed'),
  ('My date wants to exchange phone passwords once we''re exclusive.', 'relationship', false, 'approved', 'seed'),
  ('My friend wants everyone to pay for their portion of a trip even though they canceled.', 'friendship', false, 'approved', 'seed'),
  ('My partner wants us to share locations permanently once we''re married.', 'relationship', false, 'approved', 'seed'),
  ('My coworker asks for feedback but argues with every piece of it.', 'career', false, 'approved', 'seed'),
  ('My partner watches the next episode without me and then pretends they haven''t seen it.', 'relationship', false, 'approved', 'seed'),
  ('My sibling earns more than me but still expects our parents to pay for family vacations.', 'family', false, 'approved', 'seed'),
  ('My partner leaves cabinet doors open after taking something out.', 'relationship', false, 'approved', 'seed'),
  ('My friend invited my ex to a party without warning me.', 'friendship', false, 'approved', 'seed'),
  ('My partner constantly falls asleep during movies, so I finished our show without them.', 'relationship', false, 'approved', 'seed'),
  ('My parents think moving far away from family for a job is selfish.', 'family', false, 'approved', 'seed'),
  ('My partner expects me to defend them publicly even when I think they''re wrong.', 'relationship', false, 'approved', 'seed'),
  ('My coworker told me they''re interviewing elsewhere and asked me to keep it secret.', 'career', false, 'approved', 'seed'),
  ('My partner secretly checked who recently followed me on Instagram.', 'relationship', false, 'approved', 'seed'),
  ('My coworker never attends office social events but expects everyone to attend theirs.', 'career', false, 'approved', 'seed'),
  ('Someone I''m dating doesn''t drink and doesn''t want a partner who drinks either.', 'relationship', false, 'approved', 'seed'),
  ('My friend borrowed money months ago but keeps posting expensive dinners.', 'friendship', false, 'approved', 'seed'),
  ('My parents expect to know whenever my partner and I have an argument.', 'family', false, 'approved', 'seed'),
  ('My partner expects me to text when I arrive anywhere, every single time.', 'relationship', false, 'approved', 'seed'),
  ('My manager gave me a great performance review but no raise.', 'career', false, 'approved', 'seed'),
  ('A first date asked my salary before asking what I do for fun.', 'relationship', false, 'approved', 'seed'),
  ('My friend keeps score of who paid the last time we went out.', 'friendship', false, 'approved', 'seed'),
  ('My partner won''t delete dating apps because they say they only use them to look at old messages.', 'relationship', false, 'approved', 'seed'),
  ('My parents expect me to spend every major holiday with them.', 'family', false, 'approved', 'seed'),
  ('My friend expects immediate replies but sometimes leaves me on read for days.', 'friendship', false, 'approved', 'seed'),
  ('My sibling thinks family members shouldn''t need invitations to visit each other''s homes.', 'family', false, 'approved', 'seed'),
  ('My manager expects us to answer messages while we''re on vacation if it''s urgent.', 'career', false, 'approved', 'seed'),
  ('My partner thinks any purchase over $500 should require both people''s approval after marriage.', 'relationship', false, 'approved', 'seed'),
  ('My coworker refuses to share notes from meetings I couldn''t attend.', 'career', false, 'approved', 'seed'),
  ('My sibling expects me to help pay their wedding expenses because I''m doing better financially.', 'family', false, 'approved', 'seed'),
  ('My partner says they don''t want dessert and then eats half of mine.', 'relationship', false, 'approved', 'seed'),
  ('My friend keeps giving me career advice even though I never ask for it.', 'friendship', false, 'approved', 'seed'),
  ('My parents want me to live near them after I have children.', 'family', false, 'approved', 'seed'),
  ('My partner never finishes a show but constantly starts new ones.', 'relationship', false, 'approved', 'seed'),
  ('My friend takes 100 photos before letting anyone eat.', 'friendship', false, 'approved', 'seed'),
  ('My partner wants separate bedrooms after we get married because they sleep better alone.', 'relationship', false, 'approved', 'seed'),
  ('I accidentally learned what my coworker earns and it''s much more than me for the same job. Should I use it in salary negotiations?', 'career', false, 'approved', 'seed'),
  ('My friend wants me to return an expensive gift after our friendship ended.', 'friendship', false, 'approved', 'seed'),
  ('My parents expect me to send them money every month once I start earning well.', 'family', false, 'approved', 'seed'),
  ('My coworker brought their partner to an office event that said employees only.', 'career', false, 'approved', 'seed'),
  ('My friend never pays me back, so I deducted what they owed from what I owed them without asking.', 'friendship', false, 'approved', 'seed'),
  ('My manager says leaving exactly at 5 every day shows a lack of ambition.', 'career', false, 'approved', 'seed'),
  ('My date didn''t offer to pay but expected me to drive us both home.', 'relationship', false, 'approved', 'seed'),
  ('My sibling expects me to keep their secrets from our parents.', 'family', false, 'approved', 'seed'),
  ('My partner wants a weekly "relationship meeting" to discuss what''s working and what isn''t.', 'relationship', false, 'approved', 'seed'),
  ('My best friend dislikes my partner, but my partner dislikes my best friend too.', 'friendship', false, 'approved', 'seed'),
  ('My manager rejected my vacation because another teammate already requested the same week.', 'career', false, 'approved', 'seed'),
  ('My parents paid for my sibling''s wedding but say they can''t afford to help with mine.', 'family', false, 'approved', 'seed'),
  ('My manager said promotions require being "visible" in the office even though we''re hybrid.', 'career', false, 'approved', 'seed'),
  ('Someone I''m dating has cheated in every previous relationship but says they''ve changed.', 'relationship', false, 'approved', 'seed'),
  ('My sibling expects their kids to receive gifts on my birthday too so they don''t feel left out.', 'family', false, 'approved', 'seed'),
  ('My coworker takes credit for my ideas. I stopped sharing ideas with them before meetings.', 'career', false, 'approved', 'seed'),
  ('My partner wants me to stop being friends with someone because they "get a bad feeling" about them.', 'relationship', false, 'approved', 'seed'),
  ('My friend asked me not to become friends with their other friends.', 'friendship', false, 'approved', 'seed'),
  ('My sibling wants our parents to stop helping me financially because they didn''t get the same help.', 'family', false, 'approved', 'seed'),
  ('My partner thinks bachelor and bachelorette parties should have zero rules.', 'relationship', false, 'approved', 'seed'),
  ('My sibling borrowed money from me and then bought a luxury item.', 'family', false, 'approved', 'seed'),
  ('My manager praises people publicly but gives criticism only in private.', 'career', false, 'approved', 'seed'),
  ('I know my sibling''s partner plans to propose, but my sibling just told me they''re questioning the relationship. Should I warn the partner?', 'family', false, 'approved', 'seed'),
  ('My partner doesn''t want kids but says they might change their mind for me.', 'relationship', false, 'approved', 'seed'),
  ('My friend wants to split an Airbnb equally even though some people have private rooms and others don''t.', 'friendship', false, 'approved', 'seed'),
  ('My coworker regularly logs off early but gets all their work done.', 'career', false, 'approved', 'seed'),
  ('My date asked whether I''d quit my job to raise kids someday.', 'relationship', false, 'approved', 'seed'),
  ('My coworker never volunteers but complains about how projects are run.', 'career', false, 'approved', 'seed'),
  ('My parents criticize every decision I make, so I stopped telling them things until after they happen.', 'family', false, 'approved', 'seed'),
  ('My friend expects me to cancel plans when they''re having a bad day.', 'friendship', false, 'approved', 'seed'),
  ('My coworker schedules messages to look like they''re working late.', 'career', false, 'approved', 'seed'),
  ('My friend wants reimbursement for groceries they bought while I stayed at their house.', 'friendship', false, 'approved', 'seed'),
  ('My partner wants to invite their ex to our wedding because they remained friends.', 'relationship', false, 'approved', 'seed'),
  ('My sibling wants me to contribute to our parents'' expenses even though I live far away.', 'family', false, 'approved', 'seed'),
  ('My partner hates surprises, but I planned a surprise birthday party because everyone else wanted one.', 'relationship', false, 'approved', 'seed'),
  ('My parents still expect me to follow their house rules when I visit as an adult.', 'family', false, 'approved', 'seed'),
  ('Someone I''m dating takes hours to reply but is constantly active online.', 'relationship', false, 'approved', 'seed'),
  ('My family expects me at every event, so sometimes I say I''m busy when I really just want to stay home.', 'family', false, 'approved', 'seed'),
  ('My partner doesn''t want to post me online but posts everything else.', 'relationship', false, 'approved', 'seed'),
  ('My coworker refuses to connect with colleagues on social media.', 'career', false, 'approved', 'seed'),
  ('My friend thinks couples should split everything 50/50 regardless of income.', 'friendship', false, 'approved', 'seed'),
  ('My parents think I should forgive a relative because "you only get one family."', 'family', false, 'approved', 'seed'),
  ('My manager follows everyone on the team on Instagram.', 'career', false, 'approved', 'seed'),
  ('My partner wants to stay friends with someone who openly admitted having feelings for them.', 'relationship', false, 'approved', 'seed'),
  ('My friend says married people shouldn''t take solo vacations.', 'friendship', false, 'approved', 'seed'),
  ('My partner wants us to split rent based on income instead of 50/50.', 'relationship', false, 'approved', 'seed'),
  ('My roommate sets the thermostat to their preferred temperature and hides the remote.', 'friendship', false, 'approved', 'seed'),
  ('My sibling expects me to babysit whenever they''re in a bind because "family helps family."', 'family', false, 'approved', 'seed'),
  ('My manager asks the team to share personal weekend plans every Monday.', 'career', false, 'approved', 'seed'),
  ('My friend shared something I told them privately with their partner.', 'friendship', false, 'approved', 'seed'),
  ('My partner starts cleaning right before guests arrive and suddenly becomes everyone''s manager.', 'relationship', false, 'approved', 'seed'),
  ('My coworker uses AI for almost every email they send.', 'career', false, 'approved', 'seed'),
  ('My parents expect my partner to call them regularly even without me.', 'family', false, 'approved', 'seed'),
  ('My partner earns twice what I do but wants every shared expense split equally.', 'relationship', false, 'approved', 'seed'),
  ('My parents want grandchildren and bring it up almost every time I visit.', 'family', false, 'approved', 'seed'),
  ('My roommate watches videos out loud instead of using headphones.', 'friendship', false, 'approved', 'seed'),
  ('My coworker never contributes to group gifts, so we stopped putting their name on the card.', 'career', false, 'approved', 'seed'),
  ('My sibling thinks family should forgive things that would end a friendship.', 'family', false, 'approved', 'seed'),
  ('My coworker takes credit for ideas we brainstorm together.', 'career', false, 'approved', 'seed'),
  ('My roommate starts doing dishes while I''m still cooking.', 'friendship', false, 'approved', 'seed'),
  ('My parents believe children should financially support them in retirement.', 'family', false, 'approved', 'seed'),
  ('My coworker took sick leave and posted vacation photos the same day.', 'career', false, 'approved', 'seed'),
  ('My friend started a business extremely similar to an idea I told them about.', 'friendship', false, 'approved', 'seed'),
  ('My sibling constantly borrows my clothes, so I hid my favorite ones before they visited.', 'family', false, 'approved', 'seed'),
  ('I found out my friend is being cheated on, but I barely know their partner. Should I tell them?', 'friendship', false, 'approved', 'seed'),
  ('My partner expects us to vacation with their family every year.', 'relationship', false, 'approved', 'seed'),
  ('My sibling wants equal inheritance even though I''ve been our parents'' primary caregiver.', 'family', false, 'approved', 'seed'),
  ('Someone I''m dating says they never apologize unless they believe they were 100% wrong.', 'relationship', false, 'approved', 'seed'),
  ('My friend is always "five minutes away" for at least twenty minutes.', 'friendship', false, 'approved', 'seed'),
  ('My manager asks us to share our goals for the next five years.', 'career', false, 'approved', 'seed'),
  ('My friend posts photos where they look great even when everyone else looks terrible.', 'friendship', false, 'approved', 'seed'),
  ('My date said they don''t believe men and women can be "just friends."', 'relationship', false, 'approved', 'seed');
