-- Seed data for SUS MVP.
-- Run in Supabase SQL editor AFTER schema.sql.
-- 656 starter cards (56 hand-written + a 100-card batch added 2026-07-28 +
-- a 500-card batch added 2026-10-02 — see supabase/seed_batch_2026-10-02.sql
-- for that batch on its own, applied directly against production to refill
-- the pool once real devices had voted through most of the earlier 184
-- approved posts), status='approved' so they're live immediately. Five
-- generic themes (relationship/friendship/career/family/other), not
-- dating-exclusive. Keep every card under 180 characters (see
-- MAX_CONFESSION_LENGTH in src/lib/moderation.js) to match the UI.
--
-- The 2026-10-02 batch is original content written in the voice of the
-- existing cards (short, anonymized, situation-not-person) — not scraped
-- from Reddit or anywhere else. Every single line was run through the live
-- submit-post moderation function (supabase/functions/submit-post/index.ts)
-- before insertion, since a direct seed insert bypasses that Edge Function
-- entirely; all 500 came back 'approve' with zero edits needed to the
-- moderation code itself.
--
-- To add another batch: put the new questions in a .txt/.csv/.json file and
-- run `node scripts/import-seed-cards.mjs <file>` — it validates, dedupes
-- against everything already here, categorizes, and writes a ready insert
-- block you can paste below (or run directly against the DB).

insert into posts (text, category, safety_flag, status, source) values
  ('He still texts his ex every Sunday, says it''s just checking in.', 'relationship', false, 'approved', 'seed'),
  ('She reads my messages at 3am and says she wasn''t checking up on me.', 'relationship', false, 'approved', 'seed'),
  ('He replies ''k'' to texts but posts a new story every hour.', 'relationship', false, 'approved', 'seed'),
  ('My roommate borrows my stuff and ''forgets'' to ask, every week.', 'friendship', false, 'approved', 'seed'),
  ('He split the bill on the first date, down to the exact rupee.', 'relationship', false, 'approved', 'seed'),
  ('My best friend only texts me when she needs a favor.', 'friendship', false, 'approved', 'seed'),
  ('My mom reads my texts, says it''s her right since she pays my bill.', 'family', false, 'approved', 'seed'),
  ('He never apologizes first, even when he''s clearly wrong.', 'relationship', false, 'approved', 'seed'),
  ('She still keeps every gift from her ex ''for sentimental reasons.''', 'relationship', false, 'approved', 'seed'),
  ('My coworker takes credit for my ideas in every meeting.', 'career', false, 'approved', 'seed'),
  ('He wants the password to all my socials ''for trust.''', 'relationship', false, 'approved', 'seed'),
  ('My in-laws want to pick where we live without asking us.', 'family', false, 'approved', 'seed'),
  ('She cancels plans last minute but gets upset if I make other ones.', 'friendship', false, 'approved', 'seed'),
  ('He ''forgot'' his wallet on the third date in a row.', 'relationship', false, 'approved', 'seed'),
  ('My partner tracks every rupee I spend and asks for receipts.', 'relationship', false, 'approved', 'seed'),
  ('He goes silent for days after every small disagreement.', 'relationship', false, 'approved', 'seed'),
  ('She talks about me to mutual friends, then acts normal to my face.', 'friendship', false, 'approved', 'seed'),
  ('My boss messages me ''urgent'' tasks at 11pm on weekends.', 'career', false, 'approved', 'seed'),
  ('He gets annoyed if I hang out with guy friends, has girl ''best friends'' himself.', 'relationship', false, 'approved', 'seed'),
  ('My friend takes forever to pay me back and never brings it up first.', 'friendship', false, 'approved', 'seed'),
  ('She love-bombed me with gifts in week one, now barely replies.', 'relationship', false, 'approved', 'seed'),
  ('He compares me to his mother''s cooking, constantly.', 'relationship', false, 'approved', 'seed'),
  ('My sister read my diary and still brings up what she found, years later.', 'family', false, 'approved', 'seed'),
  ('He wants to know my exact schedule every day, calls it ''just curious.''', 'relationship', false, 'approved', 'seed'),
  ('She only compliments me when I''m doing worse than her.', 'friendship', false, 'approved', 'seed'),
  ('My date insisted on ordering for me without asking what I wanted.', 'relationship', false, 'approved', 'seed'),
  ('He keeps a running tally of who paid for what, every single time.', 'relationship', false, 'approved', 'seed'),
  ('My roommate never buys groceries but eats everyone else''s food.', 'friendship', false, 'approved', 'seed'),
  ('She talks over me in every group conversation, every time.', 'friendship', false, 'approved', 'seed'),
  ('He says he''s ''not the jealous type'' then interrogates me about every text.', 'relationship', false, 'approved', 'seed'),
  ('My parents want my salary slips every month, I''m 27 and independent.', 'family', false, 'approved', 'seed'),
  ('He ghosted for three weeks, came back like nothing happened.', 'relationship', false, 'approved', 'seed'),
  ('My friend group has a chat I got removed from, no explanation.', 'friendship', false, 'approved', 'seed'),
  ('She never says sorry first, waits for me to cave every time.', 'relationship', false, 'approved', 'seed'),
  ('He wants to split the ring cost but expects my family to fund the wedding.', 'relationship', false, 'approved', 'seed'),
  ('My manager takes credit for the team''s work in front of leadership.', 'career', false, 'approved', 'seed'),
  ('He checks who liked my posts and messages them if it''s a guy.', 'relationship', false, 'approved', 'seed'),
  ('She ''jokes'' about my weight in front of our whole friend group.', 'friendship', false, 'approved', 'seed'),
  ('My partner wants a joint account before we''re even engaged.', 'relationship', false, 'approved', 'seed'),
  ('He calls me ''dramatic'' every time I bring up something that hurt me.', 'relationship', false, 'approved', 'seed'),
  ('My cousin only calls when she needs to borrow money.', 'family', false, 'approved', 'seed'),
  ('He wants to meet my parents after two weeks, already talks marriage.', 'relationship', false, 'approved', 'seed'),
  ('She disappears for hours with no explanation, gets defensive if asked.', 'relationship', false, 'approved', 'seed'),
  ('My coworker screenshots our DMs and shares them with the group.', 'career', false, 'approved', 'seed'),
  ('He says ''I''m not like your ex'' unprompted, multiple times a week.', 'relationship', false, 'approved', 'seed'),
  ('My friend only remembers my birthday when I remind her first.', 'friendship', false, 'approved', 'seed'),
  ('He gets quiet and cold for hours if I disagree with him in public.', 'relationship', false, 'approved', 'seed'),
  ('She asked me to co-sign a loan for her ''business idea.''', 'friendship', false, 'approved', 'seed'),
  ('My dad compares my grades to my cousin''s in front of every guest.', 'family', false, 'approved', 'seed'),
  ('He introduces me as his girlfriend but says ''no labels'' to my face.', 'relationship', false, 'approved', 'seed'),
  ('My friend cancels on me but shows up for everyone else, every time.', 'friendship', false, 'approved', 'seed'),
  ('He wants me to send my location 24/7 ''for safety,'' won''t share his.', 'relationship', true, 'approved', 'seed'),
  ('She shows up uninvited to places I mentioned, calls it a surprise.', 'relationship', true, 'approved', 'seed'),
  ('He slowly stopped me from seeing my friends over a few months.', 'relationship', true, 'approved', 'seed'),
  ('My partner reads through my phone every time I''m asleep.', 'relationship', true, 'approved', 'seed'),
  ('He gets upset if I don''t reply within minutes, calls it ''caring.''', 'relationship', true, 'approved', 'seed');

-- Batch 2 — 100 dating/relationship/marriage/in-law cards added 2026-07-28.
-- Generated via scripts/import-seed-cards.mjs from scripts/batch-2026-07-28-dating-relationships.csv
-- (see that file for the raw source list, or scripts/ for the reusable import tool
-- to add the next batch the same way).

insert into posts (text, category, safety_flag, status, source) values
  ('He asked me to brush my teeth because he could smell the chicken I had for lunch.', 'relationship', false, 'approved', 'seed'),
  ('She asked me to send a mirror selfie every time I went out.', 'relationship', false, 'approved', 'seed'),
  ('He wanted my live location before we were officially dating.', 'relationship', false, 'approved', 'seed'),
  ('She Venmo requested me for half the coffee after inviting me out.', 'relationship', false, 'approved', 'seed'),
  ('He introduced me as "just a friend" after eight months together.', 'friendship', false, 'approved', 'seed'),
  ('She asked for my phone password on our third date.', 'relationship', false, 'approved', 'seed'),
  ('He wanted to FaceTime every night until we fell asleep.', 'relationship', false, 'approved', 'seed'),
  ('She already knew my salary before our first date because she asked mutual friends.', 'career', false, 'approved', 'seed'),
  ('He told me to stop liking other women''s Instagram photos.', 'relationship', false, 'approved', 'seed'),
  ('She canceled our date because Mercury was in retrograde.', 'relationship', false, 'approved', 'seed'),
  ('He brought his mom to our first meeting without telling me.', 'family', false, 'approved', 'seed'),
  ('She said she''d never date someone shorter than 6 feet.', 'relationship', false, 'approved', 'seed'),
  ('He expected me to reply within five minutes, even during work.', 'relationship', false, 'approved', 'seed'),
  ('She asked me to delete every dating app while she still had hers.', 'relationship', false, 'approved', 'seed'),
  ('He ranked my friends from prettiest to least attractive.', 'friendship', false, 'approved', 'seed'),
  ('She refused to split the bill because "the man should always pay."', 'relationship', false, 'approved', 'seed'),
  ('He asked how much I had in savings on our second date.', 'relationship', false, 'approved', 'seed'),
  ('She wanted to video call before I went to bed every night.', 'relationship', false, 'approved', 'seed'),
  ('He said my laugh was too loud for restaurants.', 'relationship', false, 'approved', 'seed'),
  ('She got upset because I didn''t post her on Instagram after two weeks.', 'relationship', false, 'approved', 'seed'),
  ('He asked me not to wear shorts around his friends.', 'friendship', false, 'approved', 'seed'),
  ('She wanted me to stop talking to my female coworkers.', 'career', false, 'approved', 'seed'),
  ('He expected good morning and good night texts every single day.', 'relationship', false, 'approved', 'seed'),
  ('She asked if I''d convert religions before we even became exclusive.', 'relationship', false, 'approved', 'seed'),
  ('He called me "wife material" after knowing me for three days.', 'relationship', false, 'approved', 'seed'),
  ('She checked my phone while I was in the shower.', 'relationship', false, 'approved', 'seed'),
  ('He still texted his ex every day because they were "best friends."', 'friendship', false, 'approved', 'seed'),
  ('She expected me to share my location 24/7.', 'relationship', false, 'approved', 'seed'),
  ('He refused to introduce me to his family after two years together.', 'family', false, 'approved', 'seed'),
  ('She compared everything I did to her ex.', 'relationship', false, 'approved', 'seed'),
  ('He got upset because I wanted one weekend to myself.', 'relationship', false, 'approved', 'seed'),
  ('She expected me to ask permission before making plans with friends.', 'friendship', false, 'approved', 'seed'),
  ('He joked about breaking up whenever we argued.', 'relationship', false, 'approved', 'seed'),
  ('She expected me to pay for every vacation because I earned more.', 'relationship', false, 'approved', 'seed'),
  ('He forgot my birthday but remembered his fantasy football draft.', 'relationship', false, 'approved', 'seed'),
  ('She wanted access to my bank account after six months together.', 'relationship', false, 'approved', 'seed'),
  ('He got jealous of my dog because I gave it too much attention.', 'relationship', false, 'approved', 'seed'),
  ('She asked me to stop going to the gym because other women might look at me.', 'relationship', false, 'approved', 'seed'),
  ('He insisted we share one social media account as a couple.', 'relationship', false, 'approved', 'seed'),
  ('She got angry because I didn''t answer while I was driving.', 'relationship', false, 'approved', 'seed'),
  ('He expected me to cook every meal because "that''s your thing."', 'relationship', false, 'approved', 'seed'),
  ('She read every notification that popped up on my phone.', 'relationship', false, 'approved', 'seed'),
  ('He refused to attend any of my family events.', 'family', false, 'approved', 'seed'),
  ('She expected expensive gifts every month.', 'relationship', false, 'approved', 'seed'),
  ('He wanted to know every person I had ever dated.', 'relationship', false, 'approved', 'seed'),
  ('She got upset because I liked spending time alone.', 'relationship', false, 'approved', 'seed'),
  ('He always ordered for me without asking what I wanted.', 'relationship', false, 'approved', 'seed'),
  ('She criticized every outfit I wore.', 'relationship', false, 'approved', 'seed'),
  ('He told me therapy was only for weak people.', 'relationship', false, 'approved', 'seed'),
  ('She wanted me to stop hanging out with my childhood friends.', 'friendship', false, 'approved', 'seed'),
  ('He expected me to move in with his parents immediately after marriage.', 'family', false, 'approved', 'seed'),
  ('She said my parents couldn''t visit without asking first.', 'family', false, 'approved', 'seed'),
  ('His mom wanted a copy of our house keys.', 'family', false, 'approved', 'seed'),
  ('She expected me to hand over my salary after marriage.', 'career', false, 'approved', 'seed'),
  ('He wanted every decision approved by his parents.', 'family', false, 'approved', 'seed'),
  ('She expected me to spend every festival with her family.', 'family', false, 'approved', 'seed'),
  ('He wanted us to share one bank account and close the others.', 'relationship', false, 'approved', 'seed'),
  ('She said she''d quit working whether we could afford it or not.', 'relationship', false, 'approved', 'seed'),
  ('He expected me to cook for his entire family every weekend.', 'family', false, 'approved', 'seed'),
  ('She refused to learn my family''s language.', 'family', false, 'approved', 'seed'),
  ('He told me my career would always come second to his.', 'relationship', false, 'approved', 'seed'),
  ('She expected me to move cities without discussing it.', 'relationship', false, 'approved', 'seed'),
  ('He wanted children within the first year no matter what.', 'relationship', false, 'approved', 'seed'),
  ('She expected separate vacations with her family every year.', 'family', false, 'approved', 'seed'),
  ('He asked me to stop eating meat after marriage because his family is vegetarian.', 'family', false, 'approved', 'seed'),
  ('She wanted my parents to ask for permission before visiting.', 'family', false, 'approved', 'seed'),
  ('He refused to help with housework because he worked full-time.', 'relationship', false, 'approved', 'seed'),
  ('She expected me to buy a house before getting engaged.', 'relationship', false, 'approved', 'seed'),
  ('He wanted his parents involved in every argument we had.', 'family', false, 'approved', 'seed'),
  ('She wanted separate bedrooms because she values personal space.', 'relationship', false, 'approved', 'seed'),
  ('He expected me to wear traditional clothes whenever his parents visited.', 'family', false, 'approved', 'seed'),
  ('She wanted me to change my last name immediately.', 'relationship', false, 'approved', 'seed'),
  ('He expected me to relocate overseas without asking what I wanted.', 'relationship', false, 'approved', 'seed'),
  ('She wanted to plan our entire future before we got engaged.', 'relationship', false, 'approved', 'seed'),
  ('He told me he wouldn''t attend couples counseling if we ever needed it.', 'relationship', false, 'approved', 'seed'),
  ('She unfollowed people from my Instagram without asking me.', 'relationship', false, 'approved', 'seed'),
  ('He posted every fight we had as vague stories online.', 'relationship', false, 'approved', 'seed'),
  ('She wanted me to stop being friends with my ex-roommate.', 'friendship', false, 'approved', 'seed'),
  ('He read every group chat over my shoulder.', 'relationship', false, 'approved', 'seed'),
  ('She expected me to answer calls even during work meetings.', 'career', false, 'approved', 'seed'),
  ('He refused to take pictures of me on vacation.', 'relationship', false, 'approved', 'seed'),
  ('She expected me to like every photo she posted.', 'relationship', false, 'approved', 'seed'),
  ('He got upset because I went on a solo trip.', 'relationship', false, 'approved', 'seed'),
  ('She asked me to remove every photo with my ex.', 'relationship', false, 'approved', 'seed'),
  ('He always checked who viewed my Instagram stories.', 'relationship', false, 'approved', 'seed'),
  ('She expected me to spend every weekend with her friends.', 'friendship', false, 'approved', 'seed'),
  ('He secretly recorded our arguments.', 'relationship', false, 'approved', 'seed'),
  ('She posted our private conversations online for advice.', 'relationship', false, 'approved', 'seed'),
  ('He got upset because I muted our family WhatsApp group.', 'family', false, 'approved', 'seed'),
  ('She expected me to ask before buying anything over $100.', 'relationship', false, 'approved', 'seed'),
  ('He always joked about my appearance in front of friends.', 'friendship', false, 'approved', 'seed'),
  ('She refused to attend my best friend''s wedding.', 'friendship', false, 'approved', 'seed'),
  ('He expected me to answer every call from his parents immediately.', 'family', false, 'approved', 'seed'),
  ('She wanted me to delete every female contact I didn''t actively talk to.', 'relationship', false, 'approved', 'seed'),
  ('He used my phone to reply to people pretending to be me.', 'relationship', false, 'approved', 'seed'),
  ('She got upset because I turned my read receipts off.', 'relationship', false, 'approved', 'seed'),
  ('He refused to apologize because he believed the older partner never should.', 'relationship', false, 'approved', 'seed'),
  ('She expected me to share every password "because couples shouldn''t have secrets."', 'relationship', false, 'approved', 'seed'),
  ('He blocked me after every argument and unblocked me the next day.', 'relationship', false, 'approved', 'seed'),
  ('She said if I truly loved her, I''d never need time to myself.', 'relationship', false, 'approved', 'seed');
