-- 500-card seed batch added 2026-10-02 to refill the approved pool after
-- real devices had voted through most of the original 184 approved posts
-- (get_feed() correctly excludes already-voted posts per device, so this
-- showed up to users as the feed saying 'all caught up' sooner than
-- intended, not as a bug in the feed/refresh logic itself).
--
-- Original content written in the voice of the existing seed cards —
-- short, anonymized, situation-not-person — not scraped from Reddit or
-- anywhere else. Every line was run through the live submit-post
-- moderation function before insertion, since a direct seed insert
-- bypasses that Edge Function entirely; all 500 returned 'approve' with
-- no changes needed to the moderation code.
-- Applied directly against production; included here for version control.

insert into posts (text, category, safety_flag, status, source) values
  ('He still has his ex''s number saved under a fake name in his phone.', 'relationship', false, 'approved', 'seed'),
  ('She reads my texts over my shoulder and says she''s ''just curious.''', 'relationship', false, 'approved', 'seed'),
  ('He never plans dates, just asks what I want to do every single time.', 'relationship', false, 'approved', 'seed'),
  ('She gets mad if I hang out with my guy friends but keeps her own.', 'relationship', false, 'approved', 'seed'),
  ('He forgot our anniversary but remembered his fantasy football draft.', 'relationship', false, 'approved', 'seed'),
  ('She says ''I''m fine'' and then brings it up three days later, angrier.', 'relationship', false, 'approved', 'seed'),
  ('He still likes his ex''s Instagram posts within minutes of them going up.', 'relationship', false, 'approved', 'seed'),
  ('She wants to split every bill exactly 50/50, even when I earn way less.', 'relationship', false, 'approved', 'seed'),
  ('He never initiates affection unless he wants something first.', 'relationship', false, 'approved', 'seed'),
  ('She compares our relationship to her friends'' relationships constantly.', 'relationship', false, 'approved', 'seed'),
  ('He takes forever to reply but is clearly active on social media.', 'relationship', false, 'approved', 'seed'),
  ('She wants a joint Instagram but keeps her DMs locked away from me.', 'relationship', false, 'approved', 'seed'),
  ('He says he hates drama but starts most of it.', 'relationship', false, 'approved', 'seed'),
  ('She brings up my past mistakes every time we disagree about anything.', 'relationship', false, 'approved', 'seed'),
  ('He never says sorry, just goes quiet until I apologize first.', 'relationship', false, 'approved', 'seed'),
  ('She wants to know my location at all times but won''t share hers.', 'relationship', false, 'approved', 'seed'),
  ('He flirts with waitresses right in front of me and calls it ''friendly.''', 'relationship', false, 'approved', 'seed'),
  ('She keeps a mental tally of every favor she''s ever done for me.', 'relationship', false, 'approved', 'seed'),
  ('He canceled our plans to help his friend move, again.', 'relationship', false, 'approved', 'seed'),
  ('She says she''s not jealous but interrogates me about every female coworker.', 'relationship', false, 'approved', 'seed'),
  ('He wants to move in together but still splits rent with his ex technically.', 'relationship', false, 'approved', 'seed'),
  ('She never wants to meet my family but expects me at every one of hers.', 'relationship', false, 'approved', 'seed'),
  ('He only compliments me in front of other people, never privately.', 'relationship', false, 'approved', 'seed'),
  ('She says ''do whatever you want'' but is clearly upset if I actually do.', 'relationship', false, 'approved', 'seed'),
  ('He keeps a separate bank account and won''t tell me the balance.', 'relationship', false, 'approved', 'seed'),
  ('She brings up marriage constantly but panics when I bring up moving in.', 'relationship', false, 'approved', 'seed'),
  ('He still goes to his ex''s family events ''because they''re like family.''', 'relationship', false, 'approved', 'seed'),
  ('She wants me to change my whole personality around her parents.', 'relationship', false, 'approved', 'seed'),
  ('He never remembers small details I tell him but remembers sports stats perfectly.', 'relationship', false, 'approved', 'seed'),
  ('She gets quiet and distant for days instead of just telling me what''s wrong.', 'relationship', false, 'approved', 'seed'),
  ('He wants an open relationship but gets jealous when I talk to anyone.', 'relationship', false, 'approved', 'seed'),
  ('She posts everything about us online without ever asking first.', 'relationship', false, 'approved', 'seed'),
  ('He says ''I''m not like other guys'' way too often for someone who acts exactly like them.', 'relationship', false, 'approved', 'seed'),
  ('She expects me to plan every single date but criticizes my choices.', 'relationship', false, 'approved', 'seed'),
  ('He still has a drawer full of gifts from his ex ''for sentimental reasons.''', 'relationship', false, 'approved', 'seed'),
  ('She won''t introduce me as her partner to her coworkers, just a ''friend.''', 'relationship', false, 'approved', 'seed'),
  ('He never apologizes, just buys gifts to smooth things over.', 'relationship', false, 'approved', 'seed'),
  ('She checks my phone when I''m asleep and denies it the next morning.', 'relationship', false, 'approved', 'seed'),
  ('He wants kids someday but refuses to talk about a timeline at all.', 'relationship', false, 'approved', 'seed'),
  ('She says she trusts me but needs to see every message I send.', 'relationship', false, 'approved', 'seed'),
  ('He disappears for hours and says he ''lost track of time'' every time.', 'relationship', false, 'approved', 'seed'),
  ('She wants me to cut off a lifelong friend because she doesn''t like her.', 'relationship', false, 'approved', 'seed'),
  ('He expects dinner ready every night but never offers to cook or clean.', 'relationship', false, 'approved', 'seed'),
  ('She brings her mom into every single argument we have.', 'relationship', false, 'approved', 'seed'),
  ('He says he''ll change but nothing''s actually different six months later.', 'relationship', false, 'approved', 'seed'),
  ('She wants a big wedding but refuses to discuss how we''d pay for it.', 'relationship', false, 'approved', 'seed'),
  ('He never wants to meet in the middle, it''s always his way or nothing.', 'relationship', false, 'approved', 'seed'),
  ('She texts her ex ''just to catch up'' every few months.', 'relationship', false, 'approved', 'seed'),
  ('He gets defensive the second I bring up anything that bothers me.', 'relationship', false, 'approved', 'seed'),
  ('She wants separate finances but expects me to cover most dates.', 'relationship', false, 'approved', 'seed'),
  ('He flakes on my family events but never misses his own friends'' plans.', 'relationship', false, 'approved', 'seed'),
  ('She says ''you should just know'' instead of telling me what she needs.', 'relationship', false, 'approved', 'seed'),
  ('He keeps mentioning how hot his ex was, like it''s just a neutral fact.', 'relationship', false, 'approved', 'seed'),
  ('She wants to know everyone I talk to but gets vague about her own day.', 'relationship', false, 'approved', 'seed'),
  ('He never wants to go to therapy but says I''m ''too sensitive'' a lot.', 'relationship', false, 'approved', 'seed'),
  ('She expects me to remember every date but can''t remember mine.', 'relationship', false, 'approved', 'seed'),
  ('He says he''s busy but posts online all night instead of replying to me.', 'relationship', false, 'approved', 'seed'),
  ('She wants to combine finances but still has a secret credit card.', 'relationship', false, 'approved', 'seed'),
  ('He never wants to introduce me to his friends after over a year together.', 'relationship', false, 'approved', 'seed'),
  ('She gets upset if I don''t text ''good morning'' but rarely texts first.', 'relationship', false, 'approved', 'seed'),
  ('He says long distance ''doesn''t count'' when it comes to flirting with others.', 'relationship', false, 'approved', 'seed'),
  ('She wants a ring but says she''s ''not ready'' every time I bring up living together.', 'relationship', false, 'approved', 'seed'),
  ('He keeps score of who said sorry last, like it''s a competition.', 'relationship', false, 'approved', 'seed'),
  ('She wants me to always take her side, even when she''s clearly wrong.', 'relationship', false, 'approved', 'seed'),
  ('He never plans anything for my birthday but expects a whole celebration for his.', 'relationship', false, 'approved', 'seed'),
  ('She says she''s over her ex but still keeps all their old photos.', 'relationship', false, 'approved', 'seed'),
  ('He wants to know my passwords ''for safety'' but won''t share his.', 'relationship', false, 'approved', 'seed'),
  ('She gets cold and distant whenever I spend time with my own friends.', 'relationship', false, 'approved', 'seed'),
  ('He expects me to support his hobbies fully but mocks mine constantly.', 'relationship', false, 'approved', 'seed'),
  ('She brought up my weight during an argument about something unrelated.', 'relationship', false, 'approved', 'seed'),
  ('He says ''relax, it''s just a joke'' every time I tell him something hurt me.', 'relationship', false, 'approved', 'seed'),
  ('She wants us to look perfect online but we barely talk at home.', 'relationship', false, 'approved', 'seed'),
  ('He never wants to split chores evenly, even when we both work full time.', 'relationship', false, 'approved', 'seed'),
  ('She says I''m ''too much'' when I express how I actually feel.', 'relationship', false, 'approved', 'seed'),
  ('He keeps ''forgetting'' to tell people we''re exclusive.', 'relationship', false, 'approved', 'seed'),
  ('She wants me to always pick up when she calls, no matter what I''m doing.', 'relationship', false, 'approved', 'seed'),
  ('He never wants to plan our future but gets upset if I bring up other options.', 'relationship', false, 'approved', 'seed'),
  ('She compares me to her last partner''s financial success constantly.', 'relationship', false, 'approved', 'seed'),
  ('He says ''I''m working on myself'' but hasn''t actually changed anything.', 'relationship', false, 'approved', 'seed'),
  ('She wants total honesty but shuts down the second I''m actually honest.', 'relationship', false, 'approved', 'seed'),
  ('He never wants to celebrate my wins the way I celebrate his.', 'relationship', false, 'approved', 'seed'),
  ('She expects a grand apology but never actually apologizes herself.', 'relationship', false, 'approved', 'seed'),
  ('He wants me to drop everything whenever he''s in a bad mood.', 'relationship', false, 'approved', 'seed'),
  ('She says she doesn''t care about labels but gets upset when I say ''we''re casual.''', 'relationship', false, 'approved', 'seed'),
  ('He still has a ''maybe someday'' list of people he''s attracted to, and I found it.', 'relationship', false, 'approved', 'seed'),
  ('She wants separate vacations every year but calls it ''healthy space.''', 'relationship', false, 'approved', 'seed'),
  ('He never remembers my coffee order after three years together.', 'relationship', false, 'approved', 'seed'),
  ('She brings up breaking up every time we have even a small disagreement.', 'relationship', false, 'approved', 'seed'),
  ('He says ''you''re overreacting'' as his go-to response to literally everything.', 'relationship', false, 'approved', 'seed'),
  ('She wants me to always compliment her looks but never returns the favor.', 'relationship', false, 'approved', 'seed'),
  ('He keeps a tally of every gift he''s bought me like it''s a scoreboard.', 'relationship', false, 'approved', 'seed'),
  ('She says she wants independence but gets upset when I make plans without her.', 'relationship', false, 'approved', 'seed'),
  ('He never wants to meet my friends, says they''re ''not his vibe.''', 'relationship', false, 'approved', 'seed'),
  ('She wants to know why I''m quiet but gets mad when I actually explain.', 'relationship', false, 'approved', 'seed'),
  ('He says ''that''s just how I am'' instead of ever trying to improve.', 'relationship', false, 'approved', 'seed'),
  ('She wants a committed relationship but still swipes on dating apps ''for fun.''', 'relationship', false, 'approved', 'seed'),
  ('He keeps bringing up a past relationship like it''s some impossible standard.', 'relationship', false, 'approved', 'seed'),
  ('She says sorry but keeps doing the exact same thing a week later.', 'relationship', false, 'approved', 'seed'),
  ('He wants emotional support but never offers any back.', 'relationship', false, 'approved', 'seed'),
  ('She gets jealous of my career success but never says it directly.', 'relationship', false, 'approved', 'seed'),
  ('He thinks buying flowers fixes everything, even real ongoing issues.', 'relationship', false, 'approved', 'seed'),
  ('She wants to plan the wedding alone and just hand me a checklist.', 'relationship', false, 'approved', 'seed'),
  ('He says he hates conflict so he just avoids every hard conversation entirely.', 'relationship', false, 'approved', 'seed'),
  ('She expects me to remember her friends'' birthdays better than she does.', 'relationship', false, 'approved', 'seed'),
  ('He keeps ''forgetting'' his wallet every single time we go out.', 'relationship', false, 'approved', 'seed'),
  ('She wants a partner who ''just gets her'' instead of ever explaining what she needs.', 'relationship', false, 'approved', 'seed'),
  ('He never wants PDA but gets jealous if someone else even talks to me.', 'relationship', false, 'approved', 'seed'),
  ('She says she''s independent but relies on me for literally every decision.', 'relationship', false, 'approved', 'seed'),
  ('He keeps comparing our relationship pace to his friends who are already engaged.', 'relationship', false, 'approved', 'seed'),
  ('She wants me to text constantly during work but ignores me for hours herself.', 'relationship', false, 'approved', 'seed'),
  ('He says ''I don''t need therapy, I just need you to understand me.''', 'relationship', false, 'approved', 'seed'),
  ('She gets defensive the moment I bring up anything about the future.', 'relationship', false, 'approved', 'seed'),
  ('He wants to split the honeymoon cost but expects my parents to fund the wedding.', 'relationship', false, 'approved', 'seed'),
  ('She says she forgives me but brings it up again every single fight since.', 'relationship', false, 'approved', 'seed'),
  ('He never wants to plan date night, just expects me to suggest something.', 'relationship', false, 'approved', 'seed'),
  ('She wants to know if I''ve ever had feelings for any of my friends, constantly.', 'relationship', false, 'approved', 'seed'),
  ('He keeps ''joking'' about things that clearly bother me when I ask him to stop.', 'relationship', false, 'approved', 'seed'),
  ('She says she hates being tracked but wants my location shared 24/7.', 'relationship', false, 'approved', 'seed'),
  ('He expects me to remember his schedule perfectly but never checks mine.', 'relationship', false, 'approved', 'seed'),
  ('She wants us to look like the perfect couple for photos, nothing else.', 'relationship', false, 'approved', 'seed'),
  ('He says ''you knew I was like this when we got together'' as an excuse for everything.', 'relationship', false, 'approved', 'seed'),
  ('She gets upset if I don''t ask permission before making weekend plans.', 'relationship', false, 'approved', 'seed'),
  ('He never wants to discuss finances, just assumes everything will work out.', 'relationship', false, 'approved', 'seed'),
  ('She says she''s ''not like other girls'' while doing exactly what she criticizes in them.', 'relationship', false, 'approved', 'seed'),
  ('He wants a partner who challenges him but shuts down the moment I disagree.', 'relationship', false, 'approved', 'seed'),
  ('She keeps every text from her ex ''just in case it''s ever useful.''', 'relationship', false, 'approved', 'seed'),
  ('He says ''you''re too sensitive'' every time I bring up something real.', 'relationship', false, 'approved', 'seed'),
  ('She wants me to be more romantic but rolls her eyes at every gesture I try.', 'relationship', false, 'approved', 'seed'),
  ('He never wants to meet halfway, every compromise ends up being my idea.', 'relationship', false, 'approved', 'seed'),
  ('She brings up what I did wrong years ago whenever she''s losing an argument now.', 'relationship', false, 'approved', 'seed'),
  ('He says he''s ''not ready to label it'' after being exclusive for over a year.', 'relationship', false, 'approved', 'seed'),
  ('She wants a partner who texts first but never texts first herself.', 'relationship', false, 'approved', 'seed'),
  ('He keeps a list of everything I''ve ever done wrong, apparently.', 'relationship', false, 'approved', 'seed'),
  ('She says she wants honesty but cries every time I''m actually honest.', 'relationship', false, 'approved', 'seed'),
  ('He never remembers plans we made but remembers every plan with his friends perfectly.', 'relationship', false, 'approved', 'seed'),
  ('She wants to be the center of attention at every single event we go to.', 'relationship', false, 'approved', 'seed'),
  ('He says ''relax, nothing happened'' about things that clearly crossed a line.', 'relationship', false, 'approved', 'seed'),
  ('She brings her phone to bed and gets defensive if I even glance at it.', 'relationship', false, 'approved', 'seed'),
  ('He never wants to apologize first, even when he''s obviously wrong.', 'relationship', false, 'approved', 'seed'),
  ('She wants me to always know what''s wrong without ever telling me.', 'relationship', false, 'approved', 'seed'),
  ('He says ''you''re just like my ex'' every time we disagree about anything.', 'relationship', false, 'approved', 'seed'),
  ('She gets upset if I spend money on myself but spends freely on herself.', 'relationship', false, 'approved', 'seed'),
  ('He keeps a secret second phone and says it''s ''just for games.''', 'relationship', false, 'approved', 'seed'),
  ('She wants me to be more affectionate but pulls away every time I try.', 'relationship', false, 'approved', 'seed'),
  ('He says ''I was just being nice'' about flirting that clearly crossed a line.', 'relationship', false, 'approved', 'seed'),
  ('She wants to control what I wear when we go out ''as a couple.''', 'relationship', false, 'approved', 'seed'),
  ('He never wants to talk about the relationship, just avoids it until it blows up.', 'relationship', false, 'approved', 'seed'),
  ('She says she doesn''t need validation but fishes for compliments constantly.', 'relationship', false, 'approved', 'seed'),
  ('He keeps rescheduling our trip for his friends'' plans instead.', 'relationship', false, 'approved', 'seed'),
  ('She wants a partner who''s ambitious but gets threatened by my promotions.', 'relationship', false, 'approved', 'seed'),
  ('He says ''you''re overthinking it'' about things that are clearly real red flags.', 'relationship', false, 'approved', 'seed'),
  ('She wants me to always defend her online but gets embarrassed if I post about us.', 'relationship', false, 'approved', 'seed'),
  ('He never wants to meet my parents but talks about marriage constantly.', 'relationship', false, 'approved', 'seed'),
  ('She brings up my ex in arguments even though we''ve been broken up for years.', 'relationship', false, 'approved', 'seed'),
  ('He says he ''forgot'' to mention he had plans with his ex this weekend.', 'relationship', false, 'approved', 'seed'),
  ('She wants to split the bills evenly but always ''forgets'' her wallet.', 'relationship', false, 'approved', 'seed'),
  ('He keeps telling me to ''lighten up'' when I bring up something that genuinely hurt.', 'relationship', false, 'approved', 'seed'),
  ('She wants a partner who listens but talks over me in every conversation.', 'relationship', false, 'approved', 'seed'),
  ('He says ''you should trust me more'' right after I catch him in a small lie.', 'relationship', false, 'approved', 'seed'),
  ('She gets upset when I don''t notice small changes but never notices mine.', 'relationship', false, 'approved', 'seed'),
  ('He never wants to plan ahead, says spontaneity is ''more romantic.''', 'relationship', false, 'approved', 'seed'),
  ('She wants a committed relationship but keeps ''just friends'' with every ex.', 'relationship', false, 'approved', 'seed'),
  ('He says sorry for show but never actually changes the behavior.', 'relationship', false, 'approved', 'seed'),
  ('She keeps comparing our vacations to her coworkers'' engagement photos.', 'relationship', false, 'approved', 'seed'),
  ('He never wants to discuss the relationship''s future, just lives day to day.', 'relationship', false, 'approved', 'seed'),
  ('She wants me to remember every little thing but forgets my plans constantly.', 'relationship', false, 'approved', 'seed'),
  ('He says ''that''s just banter'' about jokes that are clearly meant to hurt.', 'relationship', false, 'approved', 'seed'),
  ('She brings up marriage on every date but panics at the word ''commitment.''', 'relationship', false, 'approved', 'seed'),
  ('He never wants to split anything evenly, it''s always convenient for him.', 'relationship', false, 'approved', 'seed'),
  ('She says she''s ''low maintenance'' but expects constant reassurance.', 'relationship', false, 'approved', 'seed'),
  ('He keeps flirting with his coworkers and calls it ''just being social.''', 'relationship', false, 'approved', 'seed'),
  ('She wants a partner who''s emotionally available but shuts down my feelings constantly.', 'relationship', false, 'approved', 'seed'),
  ('He says ''you''re being dramatic'' the moment I express any real concern.', 'relationship', false, 'approved', 'seed'),
  ('She wants me to always text updates but goes dark for hours herself.', 'relationship', false, 'approved', 'seed'),
  ('He never wants to meet my friends, but expects me at every one of his events.', 'relationship', false, 'approved', 'seed'),
  ('She brings up past arguments mid-conversation about something totally unrelated.', 'relationship', false, 'approved', 'seed'),
  ('He says he wants space but gets upset if I actually give him any.', 'relationship', false, 'approved', 'seed'),
  ('She wants me to plan the perfect proposal but hints she''d ''prefer something casual.''', 'relationship', false, 'approved', 'seed'),
  ('He keeps a list of ''what if'' people he never stopped talking to.', 'relationship', false, 'approved', 'seed'),
  ('She says she''s independent but panics if I make any decision without her.', 'relationship', false, 'approved', 'seed'),
  ('He never wants to celebrate small wins, only the big milestones.', 'relationship', false, 'approved', 'seed'),
  ('She wants me to always apologize first just to end the fight faster.', 'relationship', false, 'approved', 'seed'),
  ('He says ''you knew what you signed up for'' about habits he''s never tried to change.', 'relationship', false, 'approved', 'seed'),
  ('She brings her ex up constantly as ''just an example'' in every argument.', 'relationship', false, 'approved', 'seed'),
  ('He never wants to talk about moving in, but gets upset when I bring up living alone.', 'relationship', false, 'approved', 'seed'),
  ('She says she wants a partner, not a project, but keeps trying to change me.', 'relationship', false, 'approved', 'seed'),
  ('He keeps our relationship private online but posts everything about his friends.', 'relationship', false, 'approved', 'seed'),
  ('She wants me to remember our anniversary down to the exact hour, every year.', 'relationship', false, 'approved', 'seed'),
  ('He says ''I''m just not a texter'' but texts his friends constantly all day.', 'relationship', false, 'approved', 'seed'),
  ('She brings up how her friend''s partner proposed, every single week.', 'relationship', false, 'approved', 'seed'),
  ('He never wants to resolve an argument, just waits for me to move on first.', 'relationship', false, 'approved', 'seed'),
  ('She says she trusts me completely but still goes through my old messages.', 'relationship', false, 'approved', 'seed'),
  ('My friend only texts me when she needs something and disappears after.', 'friendship', false, 'approved', 'seed'),
  ('He borrows money constantly and never brings up paying it back first.', 'friendship', false, 'approved', 'seed'),
  ('She cancels our plans last minute but posts photos out with other people.', 'friendship', false, 'approved', 'seed'),
  ('My roommate uses my stuff without asking and ''forgets'' every time.', 'friendship', false, 'approved', 'seed'),
  ('He talks over me in every group conversation we''re both part of.', 'friendship', false, 'approved', 'seed'),
  ('She only compliments me when I''m clearly having a worse week than her.', 'friendship', false, 'approved', 'seed'),
  ('My friend group made plans without me and acted surprised I found out.', 'friendship', false, 'approved', 'seed'),
  ('He never remembers my birthday but expects a big deal made of his.', 'friendship', false, 'approved', 'seed'),
  ('She vents to me constantly but never asks how I''m actually doing.', 'friendship', false, 'approved', 'seed'),
  ('My friend takes credit for an idea I told her privately weeks ago.', 'friendship', false, 'approved', 'seed'),
  ('He''s competitive about literally everything, even things that don''t matter.', 'friendship', false, 'approved', 'seed'),
  ('She ''jokes'' about things that clearly hurt and gets mad if I react.', 'friendship', false, 'approved', 'seed'),
  ('My friend only hangs out one-on-one, never wants to meet my other friends.', 'friendship', false, 'approved', 'seed'),
  ('He flakes constantly but gets upset when I cancel on him once.', 'friendship', false, 'approved', 'seed'),
  ('She always needs to be the center of attention in every story told.', 'friendship', false, 'approved', 'seed'),
  ('My childhood friend acts like our friendship hasn''t changed since we barely talk now.', 'friendship', false, 'approved', 'seed'),
  ('He''s always ''too busy'' for me but posts hanging out with others constantly.', 'friendship', false, 'approved', 'seed'),
  ('She copies everything I do, down to the exact outfits and hobbies.', 'friendship', false, 'approved', 'seed'),
  ('My roommate''s friends are always over but she gets annoyed when mine visit.', 'friendship', false, 'approved', 'seed'),
  ('He never apologizes for being late, just shows up like it''s normal.', 'friendship', false, 'approved', 'seed'),
  ('She shares things I told her in confidence with the rest of the group.', 'friendship', false, 'approved', 'seed'),
  ('My friend only reaches out during a breakup, then vanishes once she''s happy.', 'friendship', false, 'approved', 'seed'),
  ('He gets jealous whenever I make a new friend and tries to compete for attention.', 'friendship', false, 'approved', 'seed'),
  ('She expects me to remember every detail of her life but forgets mine entirely.', 'friendship', false, 'approved', 'seed'),
  ('My friend group has an inside joke that''s really just about excluding someone.', 'friendship', false, 'approved', 'seed'),
  ('He borrows my things and returns them damaged without ever mentioning it.', 'friendship', false, 'approved', 'seed'),
  ('She gets passive aggressive instead of just telling me what''s actually wrong.', 'friendship', false, 'approved', 'seed'),
  ('My friend only invites me to things when it''s convenient for her.', 'friendship', false, 'approved', 'seed'),
  ('He talks badly about our mutual friend behind her back constantly.', 'friendship', false, 'approved', 'seed'),
  ('She expects me to drop everything whenever she''s going through something.', 'friendship', false, 'approved', 'seed'),
  ('My roommate never buys groceries but eats whatever I buy without asking.', 'friendship', false, 'approved', 'seed'),
  ('He acts completely different around different friend groups, never consistent.', 'friendship', false, 'approved', 'seed'),
  ('She gets upset if I''m close with anyone else, calls it ''replacing'' her.', 'friendship', false, 'approved', 'seed'),
  ('My friend never initiates plans but complains that we never hang out.', 'friendship', false, 'approved', 'seed'),
  ('He ''forgets'' his wallet every time we go out, every single time.', 'friendship', false, 'approved', 'seed'),
  ('She posts vague things online clearly aimed at me instead of just talking to me.', 'friendship', false, 'approved', 'seed'),
  ('My friend always one-ups every story I tell with something bigger.', 'friendship', false, 'approved', 'seed'),
  ('He ghosted for months then acted like nothing happened when he resurfaced.', 'friendship', false, 'approved', 'seed'),
  ('She never asks about my relationship but expects details about hers constantly.', 'friendship', false, 'approved', 'seed'),
  ('My roommate''s partner basically lives here now without ever discussing it.', 'friendship', false, 'approved', 'seed'),
  ('He gets defensive the second I bring up anything he did that hurt me.', 'friendship', false, 'approved', 'seed'),
  ('She only remembers my achievements if they somehow benefit her too.', 'friendship', false, 'approved', 'seed'),
  ('My friend group picked sides after an argument I wasn''t even part of.', 'friendship', false, 'approved', 'seed'),
  ('He texts constantly when bored but ignores me completely when he''s busy.', 'friendship', false, 'approved', 'seed'),
  ('She says she''s happy for me but her tone says something completely different.', 'friendship', false, 'approved', 'seed'),
  ('My friend never offers to pay but always suggests the most expensive place.', 'friendship', false, 'approved', 'seed'),
  ('He brings up my past mistakes as jokes in front of new people.', 'friendship', false, 'approved', 'seed'),
  ('She expects loyalty from me but talks about me behind my back too.', 'friendship', false, 'approved', 'seed'),
  ('My friend only wants to hang out when her other plans fall through.', 'friendship', false, 'approved', 'seed'),
  ('He never checks in during hard times but expects support during his.', 'friendship', false, 'approved', 'seed'),
  ('She gets weirdly competitive about our kids'' milestones now that we''re both parents.', 'friendship', false, 'approved', 'seed'),
  ('My roommate plays music loudly at night and acts surprised when I ask her to stop.', 'friendship', false, 'approved', 'seed'),
  ('He never remembers anything I tell him but remembers every sports statistic.', 'friendship', false, 'approved', 'seed'),
  ('She canceled on my birthday plans but showed up fully for someone else''s the next week.', 'friendship', false, 'approved', 'seed'),
  ('My friend group has a chat without me and I only found out by accident.', 'friendship', false, 'approved', 'seed'),
  ('He borrows my car and returns it on empty every single time.', 'friendship', false, 'approved', 'seed'),
  ('She says she supports me but questions every decision I make out loud.', 'friendship', false, 'approved', 'seed'),
  ('My friend only likes hanging out when we''re doing what she wants to do.', 'friendship', false, 'approved', 'seed'),
  ('He talks about his problems for hours but cuts me off the second I bring up mine.', 'friendship', false, 'approved', 'seed'),
  ('She gets upset if I don''t like her posts but never interacts with mine.', 'friendship', false, 'approved', 'seed'),
  ('My roommate invites people over without ever giving me a heads up.', 'friendship', false, 'approved', 'seed'),
  ('He never remembers plans we made unless I remind him multiple times.', 'friendship', false, 'approved', 'seed'),
  ('She makes everything a competition, even things like who''s more stressed.', 'friendship', false, 'approved', 'seed'),
  ('My friend only apologizes when I bring it up, never on her own.', 'friendship', false, 'approved', 'seed'),
  ('He acts like my accomplishments are no big deal but brags about his own.', 'friendship', false, 'approved', 'seed'),
  ('She expects me to keep her secrets but shares mine with everyone.', 'friendship', false, 'approved', 'seed'),
  ('My roommate''s cat destroyed my things and she just laughed it off.', 'friendship', false, 'approved', 'seed'),
  ('He flakes on plans constantly but gets hurt if I make plans without him.', 'friendship', false, 'approved', 'seed'),
  ('She never remembers my partner''s name after years of us dating.', 'friendship', false, 'approved', 'seed'),
  ('My friend group always defers to one person''s plans, never considers mine.', 'friendship', false, 'approved', 'seed'),
  ('He talks about me to our mutual friends in a way that''s clearly not kind.', 'friendship', false, 'approved', 'seed'),
  ('She says she''s busy but has time for everyone except me lately.', 'friendship', false, 'approved', 'seed'),
  ('My roommate uses my car without asking and returns it with a new scratch.', 'friendship', false, 'approved', 'seed'),
  ('He never offers to help but expects help from me whenever he needs it.', 'friendship', false, 'approved', 'seed'),
  ('She gets defensive the moment I point out something she did wrong.', 'friendship', false, 'approved', 'seed'),
  ('My friend only texts back when it''s convenient, hours or days later.', 'friendship', false, 'approved', 'seed'),
  ('He brings a plus-one to everything without ever asking if that''s okay first.', 'friendship', false, 'approved', 'seed'),
  ('She expects emotional support but never reciprocates when I need it.', 'friendship', false, 'approved', 'seed'),
  ('My roommate''s partner eats my food and acts like it''s completely normal.', 'friendship', false, 'approved', 'seed'),
  ('He never remembers my work stress but talks about his for hours.', 'friendship', false, 'approved', 'seed'),
  ('She gossips about everyone, which makes me wonder what she says about me.', 'friendship', false, 'approved', 'seed'),
  ('My friend only wants deep conversations when she''s upset, never otherwise.', 'friendship', false, 'approved', 'seed'),
  ('He borrows money and avoids the subject whenever I bring it up gently.', 'friendship', false, 'approved', 'seed'),
  ('She gets jealous of my other friendships but has plenty of her own.', 'friendship', false, 'approved', 'seed'),
  ('My roommate never does dishes but complains if mine sit for a day.', 'friendship', false, 'approved', 'seed'),
  ('He acts hurt that I didn''t invite him but never invites me to anything either.', 'friendship', false, 'approved', 'seed'),
  ('She only remembers the version of events where she''s the victim.', 'friendship', false, 'approved', 'seed'),
  ('My friend group never checks in on me but expects me to always show up.', 'friendship', false, 'approved', 'seed'),
  ('He talks over my stories to tell his own, every single time.', 'friendship', false, 'approved', 'seed'),
  ('She says she''d never judge me then judges every choice I make.', 'friendship', false, 'approved', 'seed'),
  ('My roommate leaves passive aggressive notes instead of just talking to me.', 'friendship', false, 'approved', 'seed'),
  ('He never remembers to ask how my family is doing, even during hard times.', 'friendship', false, 'approved', 'seed'),
  ('She expects me to always be available but is never available for me.', 'friendship', false, 'approved', 'seed'),
  ('My friend only hangs out with me when her other friends are busy.', 'friendship', false, 'approved', 'seed'),
  ('He brags about things he clearly didn''t actually do by himself.', 'friendship', false, 'approved', 'seed'),
  ('She gets upset when I set boundaries but has plenty of her own.', 'friendship', false, 'approved', 'seed'),
  ('My roommate''s guests use my things without ever asking me first.', 'friendship', false, 'approved', 'seed'),
  ('He never follows through on plans but gets defensive if I bring it up.', 'friendship', false, 'approved', 'seed'),
  ('She posts about ''fake friends'' right after we had a disagreement.', 'friendship', false, 'approved', 'seed'),
  ('My friend only remembers the favors she''s done, never the ones I''ve done.', 'friendship', false, 'approved', 'seed'),
  ('He talks about moving on from a fight but brings it up again weeks later.', 'friendship', false, 'approved', 'seed'),
  ('She expects me to celebrate her wins but minimizes mine every time.', 'friendship', false, 'approved', 'seed'),
  ('My mom reads my texts and says it''s her right since she pays my phone bill.', 'family', false, 'approved', 'seed'),
  ('My dad compares my career to my cousin''s every single family dinner.', 'family', false, 'approved', 'seed'),
  ('My sister borrows money constantly and never brings up paying it back.', 'family', false, 'approved', 'seed'),
  ('My in-laws want to choose where we live without ever asking us first.', 'family', false, 'approved', 'seed'),
  ('My parents still treat me like a kid even though I''m nearly thirty.', 'family', false, 'approved', 'seed'),
  ('My brother always takes our parents'' side no matter what the argument is.', 'family', false, 'approved', 'seed'),
  ('My mom guilt-trips me every time I don''t visit as often as she''d like.', 'family', false, 'approved', 'seed'),
  ('My dad gives unsolicited advice about my relationship constantly.', 'family', false, 'approved', 'seed'),
  ('My grandmother shares my personal news with the whole family before I do.', 'family', false, 'approved', 'seed'),
  ('My parents want detailed updates on my finances even though I''m independent.', 'family', false, 'approved', 'seed'),
  ('My sibling gets away with everything while I get blamed for small things.', 'family', false, 'approved', 'seed'),
  ('My mother-in-law shows up unannounced and expects to be let in immediately.', 'family', false, 'approved', 'seed'),
  ('My dad brings up my past mistakes at every holiday gathering.', 'family', false, 'approved', 'seed'),
  ('My cousin only calls when she needs a favor, never just to talk.', 'family', false, 'approved', 'seed'),
  ('My parents compare my life choices to my siblings'' constantly.', 'family', false, 'approved', 'seed'),
  ('My aunt shares family drama on social media before telling anyone directly.', 'family', false, 'approved', 'seed'),
  ('My mom wants my salary slips every year even though I live independently.', 'family', false, 'approved', 'seed'),
  ('My brother expects me to cover for him with our parents every time.', 'family', false, 'approved', 'seed'),
  ('My in-laws comment on our parenting choices at every single visit.', 'family', false, 'approved', 'seed'),
  ('My dad never apologizes, just acts like nothing happened the next day.', 'family', false, 'approved', 'seed'),
  ('My mom favors my younger sibling and barely hides it anymore.', 'family', false, 'approved', 'seed'),
  ('My grandparents push outdated opinions and get upset if anyone disagrees.', 'family', false, 'approved', 'seed'),
  ('My sister reads my old diary entries and still brings them up years later.', 'family', false, 'approved', 'seed'),
  ('My parents guilt me about moving away for a better job opportunity.', 'family', false, 'approved', 'seed'),
  ('My in-laws expect every holiday to be spent entirely with their side.', 'family', false, 'approved', 'seed'),
  ('My dad criticizes my partner but expects me to never say anything about his.', 'family', false, 'approved', 'seed'),
  ('My mom calls multiple times a day and gets upset if I don''t answer immediately.', 'family', false, 'approved', 'seed'),
  ('My brother borrows my car and returns it with an empty tank every time.', 'family', false, 'approved', 'seed'),
  ('My aunt gossips about every family member to every other family member.', 'family', false, 'approved', 'seed'),
  ('My parents expect me to attend every family event, no exceptions ever.', 'family', false, 'approved', 'seed'),
  ('My sister-in-law makes passive aggressive comments about my home constantly.', 'family', false, 'approved', 'seed'),
  ('My dad still controls family finances and won''t explain anything to anyone.', 'family', false, 'approved', 'seed'),
  ('My mom compares my parenting to how she raised us, constantly.', 'family', false, 'approved', 'seed'),
  ('My cousin posts about family issues online instead of talking to us directly.', 'family', false, 'approved', 'seed'),
  ('My in-laws expect us to babysit on short notice, every single weekend.', 'family', false, 'approved', 'seed'),
  ('My parents never visit but expect us to visit them every holiday.', 'family', false, 'approved', 'seed'),
  ('My sibling takes credit for things I actually did for our parents.', 'family', false, 'approved', 'seed'),
  ('My mother-in-law criticizes my cooking at every family dinner.', 'family', false, 'approved', 'seed'),
  ('My dad brings up politics at every gathering even after being asked not to.', 'family', false, 'approved', 'seed'),
  ('My aunt constantly asks when I''m having kids, even after being asked to stop.', 'family', false, 'approved', 'seed'),
  ('My brother expects financial help but never offers any in return.', 'family', false, 'approved', 'seed'),
  ('My parents favor my sibling''s career path over mine without ever saying it directly.', 'family', false, 'approved', 'seed'),
  ('My mother-in-law gives unsolicited parenting advice at every single visit.', 'family', false, 'approved', 'seed'),
  ('My sister never visits our parents but judges me for not visiting enough.', 'family', false, 'approved', 'seed'),
  ('My dad dismisses my feelings as ''overreacting'' during every conversation.', 'family', false, 'approved', 'seed'),
  ('My in-laws expect a say in decisions that are really only ours to make.', 'family', false, 'approved', 'seed'),
  ('My mom brings up my weight at every family gathering, unprompted.', 'family', false, 'approved', 'seed'),
  ('My cousin borrowed money years ago and still hasn''t brought it up since.', 'family', false, 'approved', 'seed'),
  ('My parents expect me to settle every sibling dispute between us.', 'family', false, 'approved', 'seed'),
  ('My brother-in-law makes comments about our lifestyle that feel judgmental.', 'family', false, 'approved', 'seed'),
  ('My dad never remembers my job title but remembers every detail of my brother''s.', 'family', false, 'approved', 'seed'),
  ('My grandmother shares embarrassing childhood stories at every gathering.', 'family', false, 'approved', 'seed'),
  ('My mom expects daily check-ins and gets hurt if I miss even one day.', 'family', false, 'approved', 'seed'),
  ('My in-laws show up during our vacations uninvited, every single year.', 'family', false, 'approved', 'seed'),
  ('My sibling expects me to lie to our parents to cover for them.', 'family', false, 'approved', 'seed'),
  ('My dad criticizes every decision I make but offers no actual advice.', 'family', false, 'approved', 'seed'),
  ('My mother-in-law rearranges our kitchen every time she visits without asking.', 'family', false, 'approved', 'seed'),
  ('My aunt spreads rumors about family members and denies it when confronted.', 'family', false, 'approved', 'seed'),
  ('My parents guilt-trip me for spending holidays with my partner''s family.', 'family', false, 'approved', 'seed'),
  ('My sister expects me to babysit constantly but never offers to return the favor.', 'family', false, 'approved', 'seed'),
  ('My dad brings up my ex at family dinners even years after we broke up.', 'family', false, 'approved', 'seed'),
  ('My in-laws expect updates on our finances that really aren''t their business.', 'family', false, 'approved', 'seed'),
  ('My mom compares my home to my sibling''s home every single visit.', 'family', false, 'approved', 'seed'),
  ('My brother never contributes to family gatherings but criticizes how they''re run.', 'family', false, 'approved', 'seed'),
  ('My mother-in-law hints she liked my partner''s ex better, more than once.', 'family', false, 'approved', 'seed'),
  ('My dad never asks about my life but talks about his for hours.', 'family', false, 'approved', 'seed'),
  ('My cousin shows up to events uninvited and acts surprised when it''s awkward.', 'family', false, 'approved', 'seed'),
  ('My parents expect me to choose between them during every single disagreement.', 'family', false, 'approved', 'seed'),
  ('My sister-in-law excludes me from family plans but acts confused when I ask why.', 'family', false, 'approved', 'seed'),
  ('My grandfather makes outdated comments and gets defensive if anyone pushes back.', 'family', false, 'approved', 'seed'),
  ('My mom brings up grandchildren at every holiday, even after being asked to stop.', 'family', false, 'approved', 'seed'),
  ('My dad expects loyalty but rarely shows any support in return.', 'family', false, 'approved', 'seed'),
  ('My in-laws critique our life choices but never offer any actual help.', 'family', false, 'approved', 'seed'),
  ('My brother only calls our parents when he needs something from them.', 'family', false, 'approved', 'seed'),
  ('My coworker takes credit for my ideas in nearly every single meeting.', 'career', false, 'approved', 'seed'),
  ('My manager assigns me extra work but gives the recognition to someone else.', 'career', false, 'approved', 'seed'),
  ('My boss messages me about ''urgent'' tasks late at night and on weekends.', 'career', false, 'approved', 'seed'),
  ('My coworker constantly complains about workload but takes the longest lunches.', 'career', false, 'approved', 'seed'),
  ('My manager plays favorites so obviously that the whole team notices.', 'career', false, 'approved', 'seed'),
  ('My coworker oversharing personal drama has become the whole office''s business.', 'career', false, 'approved', 'seed'),
  ('I found out a coworker with less experience makes significantly more than me.', 'career', false, 'approved', 'seed'),
  ('My boss takes credit for the team''s work in front of leadership every time.', 'career', false, 'approved', 'seed'),
  ('My coworker is always late but somehow never gets called out for it.', 'career', false, 'approved', 'seed'),
  ('My manager micromanages every detail after one small mistake months ago.', 'career', false, 'approved', 'seed'),
  ('My coworker asks for personal favors constantly but never returns them.', 'career', false, 'approved', 'seed'),
  ('My boss expects instant replies after hours but is slow to respond during work.', 'career', false, 'approved', 'seed'),
  ('My coworker undermines my ideas in meetings then repeats them later as their own.', 'career', false, 'approved', 'seed'),
  ('My manager gave the promotion to someone less qualified but more vocal.', 'career', false, 'approved', 'seed'),
  ('My coworker borrows supplies and never returns them, every single time.', 'career', false, 'approved', 'seed'),
  ('My boss schedules meetings that could easily just be an email, constantly.', 'career', false, 'approved', 'seed'),
  ('My coworker gossips about everyone, which makes me wonder what they say about me.', 'career', false, 'approved', 'seed'),
  ('My manager praises a coworker publicly for work I actually did.', 'career', false, 'approved', 'seed'),
  ('My coworker overshares political opinions no one asked to hear at work.', 'career', false, 'approved', 'seed'),
  ('My boss expects me to work through lunch but never acknowledges the extra effort.', 'career', false, 'approved', 'seed'),
  ('My coworker takes long breaks but complains when others take short ones.', 'career', false, 'approved', 'seed'),
  ('My manager never gives feedback until a performance review, then it''s all negative.', 'career', false, 'approved', 'seed'),
  ('My coworker name-drops our project to clients as if it were entirely their work.', 'career', false, 'approved', 'seed'),
  ('My boss cancels one-on-ones constantly but expects instant updates from me.', 'career', false, 'approved', 'seed'),
  ('My coworker constantly interrupts me in meetings to repeat my own points.', 'career', false, 'approved', 'seed'),
  ('My manager assigns the hardest tasks to me but easier ones to their favorite.', 'career', false, 'approved', 'seed'),
  ('My coworker calls in sick often but posts vacation photos the same week.', 'career', false, 'approved', 'seed'),
  ('My boss expects weekend availability but never offers comp time in return.', 'career', false, 'approved', 'seed'),
  ('My coworker takes credit in emails by replying-all with ''great idea, team.''', 'career', false, 'approved', 'seed'),
  ('My manager never remembers my accomplishments but praises others for less.', 'career', false, 'approved', 'seed'),
  ('My coworker asks me to cover their shifts constantly but never returns the favor.', 'career', false, 'approved', 'seed'),
  ('My boss gives vague feedback and then gets upset when expectations aren''t met.', 'career', false, 'approved', 'seed'),
  ('My coworker takes personal calls loudly at their desk all day long.', 'career', false, 'approved', 'seed'),
  ('My manager schedules my vacation requests around everyone else''s first.', 'career', false, 'approved', 'seed'),
  ('My coworker name-drops senior leadership to get out of doing actual work.', 'career', false, 'approved', 'seed'),
  ('My boss expects perfection but never explains what that actually looks like.', 'career', false, 'approved', 'seed'),
  ('My coworker constantly asks for help but never offers any when I need it.', 'career', false, 'approved', 'seed'),
  ('My manager takes feedback personally instead of actually addressing it.', 'career', false, 'approved', 'seed'),
  ('My coworker uses company time for personal projects, then brags about them.', 'career', false, 'approved', 'seed'),
  ('My boss promised a raise months ago and keeps pushing the conversation back.', 'career', false, 'approved', 'seed'),
  ('My coworker dumps their unfinished work on me right before deadlines.', 'career', false, 'approved', 'seed'),
  ('My manager praises ''teamwork'' but never credits the actual team members.', 'career', false, 'approved', 'seed'),
  ('My coworker takes credit for client relationships I actually built.', 'career', false, 'approved', 'seed'),
  ('My boss expects me to train new hires with zero extra time or pay.', 'career', false, 'approved', 'seed'),
  ('My coworker constantly checks their phone during meetings, visibly distracted.', 'career', false, 'approved', 'seed'),
  ('My manager only notices mistakes, never acknowledges consistent good work.', 'career', false, 'approved', 'seed'),
  ('My coworker exaggerates their contributions during every team update.', 'career', false, 'approved', 'seed'),
  ('My boss expects loyalty but has no problem laying people off without warning.', 'career', false, 'approved', 'seed'),
  ('My coworker takes long lunches then stays late to look more dedicated.', 'career', false, 'approved', 'seed'),
  ('My manager reassigned my project to someone else right before it launched.', 'career', false, 'approved', 'seed'),
  ('My coworker constantly name-drops their connections to seem more important.', 'career', false, 'approved', 'seed'),
  ('My boss expects me to answer emails instantly but takes days to respond.', 'career', false, 'approved', 'seed'),
  ('My coworker complains about everyone else''s work ethic but does the least.', 'career', false, 'approved', 'seed'),
  ('My manager gives public praise to whoever talks the most in meetings.', 'career', false, 'approved', 'seed'),
  ('My coworker takes credit for a project I spent months building alone.', 'career', false, 'approved', 'seed'),
  ('My boss schedules my reviews around their vacation, pushing them back months.', 'career', false, 'approved', 'seed'),
  ('My coworker constantly asks personal questions that feel inappropriate for work.', 'career', false, 'approved', 'seed'),
  ('My manager expects overtime but refuses to approve any actual overtime pay.', 'career', false, 'approved', 'seed'),
  ('My coworker name-drops deadlines they missed as someone else''s fault.', 'career', false, 'approved', 'seed'),
  ('My boss gives last-minute assignments then gets upset about rushed results.', 'career', false, 'approved', 'seed'),
  ('My coworker takes credit for mentoring a new hire I actually trained.', 'career', false, 'approved', 'seed'),
  ('My manager cancels team events but expects full attendance at mandatory ones.', 'career', false, 'approved', 'seed'),
  ('My coworker constantly interrupts to redirect credit back to themselves.', 'career', false, 'approved', 'seed'),
  ('My boss expects weekend emails answered but ignores mine during the week.', 'career', false, 'approved', 'seed'),
  ('My coworker borrows my notes before meetings then presents them as their own prep.', 'career', false, 'approved', 'seed'),
  ('My manager never acknowledges burnout but expects consistent peak performance.', 'career', false, 'approved', 'seed'),
  ('My coworker takes sick days around every long weekend, like clockwork.', 'career', false, 'approved', 'seed'),
  ('My boss promised flexibility but schedules everything rigidly anyway.', 'career', false, 'approved', 'seed'),
  ('My coworker constantly brings up their workload to avoid taking on anything new.', 'career', false, 'approved', 'seed'),
  ('My manager praises risk-taking but punishes anyone whose risk doesn''t pay off.', 'career', false, 'approved', 'seed'),
  ('My coworker takes credit for ideas from a brainstorm I actually led.', 'career', false, 'approved', 'seed'),
  ('My boss expects instant loyalty but offers zero job security in return.', 'career', false, 'approved', 'seed'),
  ('My coworker constantly ''forgets'' to loop me in on relevant project updates.', 'career', false, 'approved', 'seed'),
  ('My landlord enters my apartment without notice and calls it a ''quick check.''', 'other', false, 'approved', 'seed'),
  ('My neighbor plays loud music late at night and ignores every polite request.', 'other', false, 'approved', 'seed'),
  ('My landlord raised the rent significantly without making any actual improvements.', 'other', false, 'approved', 'seed'),
  ('My tenant hasn''t paid rent in months and keeps avoiding the conversation.', 'other', false, 'approved', 'seed'),
  ('My neighbor''s dog barks constantly and they act like it''s not their problem.', 'other', false, 'approved', 'seed'),
  ('My landlord takes weeks to fix basic issues but expects rent exactly on time.', 'other', false, 'approved', 'seed'),
  ('My gym buddy always skips our planned sessions but still asks for workout advice.', 'other', false, 'approved', 'seed'),
  ('My rideshare driver took a longer route and acted annoyed when I mentioned it.', 'other', false, 'approved', 'seed'),
  ('My neighbor parks in my spot constantly and acts confused when I bring it up.', 'other', false, 'approved', 'seed'),
  ('My landlord won''t return my security deposit without a clear explanation.', 'other', false, 'approved', 'seed'),
  ('My study group partner never contributes but takes equal credit on every project.', 'other', false, 'approved', 'seed'),
  ('My neighbor lets their kids play in my yard without ever asking first.', 'other', false, 'approved', 'seed'),
  ('My landlord shows up with contractors without any advance notice at all.', 'other', false, 'approved', 'seed'),
  ('My subscription-splitting roommate stopped paying their share months ago.', 'other', false, 'approved', 'seed'),
  ('My neighbor complains about noise but blasts their own music every weekend.', 'other', false, 'approved', 'seed'),
  ('My landlord ignores maintenance requests for weeks at a time.', 'other', false, 'approved', 'seed'),
  ('My gym acquaintance gives unsolicited advice about my workout every single time.', 'other', false, 'approved', 'seed'),
  ('My neighbor''s car alarm goes off constantly and they never seem to notice.', 'other', false, 'approved', 'seed'),
  ('My landlord wants to show the apartment to new tenants while I still live there.', 'other', false, 'approved', 'seed'),
  ('My carpool partner is late nearly every morning and never actually apologizes.', 'other', false, 'approved', 'seed'),
  ('My neighbor borrows tools and never returns them, even after reminders.', 'other', false, 'approved', 'seed'),
  ('My landlord increased rent right after I signed a longer lease, barely.', 'other', false, 'approved', 'seed'),
  ('My tenant keeps subletting the apartment without ever asking permission.', 'other', false, 'approved', 'seed'),
  ('My neighbor''s renovation noise starts far earlier than any reasonable hour.', 'other', false, 'approved', 'seed'),
  ('My landlord blames every maintenance issue on normal wear and tear.', 'other', false, 'approved', 'seed'),
  ('My study partner disappears before every deadline but shows up for the final presentation.', 'other', false, 'approved', 'seed'),
  ('My neighbor keeps dumping their yard waste over the fence into mine.', 'other', false, 'approved', 'seed'),
  ('My landlord charges fees that were never actually mentioned in the lease.', 'other', false, 'approved', 'seed'),
  ('My gym partner cancels last minute but still expects me to spot them later.', 'other', false, 'approved', 'seed'),
  ('My neighbor hosts loud parties on weeknights and never gives any warning.', 'other', false, 'approved', 'seed'),
  ('My landlord won''t fix the heater but still expects rent paid exactly on time.', 'other', false, 'approved', 'seed'),
  ('My rideshare driver canceled on me right as I was getting into the car.', 'other', false, 'approved', 'seed'),
  ('My neighbor''s security light shines directly into my bedroom window all night.', 'other', false, 'approved', 'seed'),
  ('My landlord wants access to my apartment ''whenever it''s convenient'' for them.', 'other', false, 'approved', 'seed'),
  ('My carpool partner never contributes gas money but always wants a ride.', 'other', false, 'approved', 'seed'),
  ('My neighbor''s fence is clearly on my property and they refuse to discuss it.', 'other', false, 'approved', 'seed'),
  ('My landlord keeps the thermostat locked at an uncomfortable temperature.', 'other', false, 'approved', 'seed'),
  ('My study group leader assigns themselves the easiest part every single time.', 'other', false, 'approved', 'seed'),
  ('My neighbor''s guests take up all the visitor parking, every single weekend.', 'other', false, 'approved', 'seed'),
  ('My landlord ignored the mold issue for months before finally addressing it.', 'other', false, 'approved', 'seed'),
  ('My tenant leaves the shared laundry room a mess and never cleans up after.', 'other', false, 'approved', 'seed'),
  ('My neighbor''s smoking drifts directly into my apartment through the vents.', 'other', false, 'approved', 'seed'),
  ('My landlord wants a same-day response but takes weeks to reply to anything.', 'other', false, 'approved', 'seed'),
  ('My gym acquaintance hogs the equipment for way longer than the posted limit.', 'other', false, 'approved', 'seed'),
  ('My neighbor''s kids ring my doorbell as a joke and then run away constantly.', 'other', false, 'approved', 'seed'),
  ('My landlord charged a cleaning fee despite me leaving the place spotless.', 'other', false, 'approved', 'seed'),
  ('My carpool partner talks on speakerphone the entire ride, every single day.', 'other', false, 'approved', 'seed'),
  ('My neighbor''s package thefts keep happening and they act like it''s not their concern.', 'other', false, 'approved', 'seed'),
  ('My landlord wants proof of income every year even for a tenant who''s never missed rent.', 'other', false, 'approved', 'seed'),
  ('My study partner takes credit during the presentation for parts they never wrote.', 'other', false, 'approved', 'seed'),
  ('He says ''calm down'' the instant I raise my voice even slightly.', 'relationship', false, 'approved', 'seed'),
  ('She wants a partner who initiates plans but never initiates any herself.', 'relationship', false, 'approved', 'seed'),
  ('He keeps a running list of my flaws that he brings up during every fight.', 'relationship', false, 'approved', 'seed'),
  ('She says she''s not mad then gives one-word answers for the rest of the night.', 'relationship', false, 'approved', 'seed'),
  ('He never wants to split the cost of gifts for my side of the family.', 'relationship', false, 'approved', 'seed'),
  ('My uncle gives financial advice nobody asked for at every single gathering.', 'family', false, 'approved', 'seed'),
  ('My stepmom compares me to her own kids at every family event.', 'family', false, 'approved', 'seed'),
  ('My manager takes long weekends but questions everyone else''s time off.', 'career', false, 'approved', 'seed'),
  ('My coworker schedules meetings over lunch and acts surprised when people are annoyed.', 'career', false, 'approved', 'seed');
