-- Seed data for SUS MVP.
-- Run in Supabase SQL editor AFTER schema.sql.
-- 56 hand-written starter cards, status='approved' so they're live immediately.
-- Generic themes (loyalty/trust/honesty/boundaries/money/family/friendship/work),
-- not dating-exclusive. Expand this before real launch — swap in more from your
-- own friend group + curated (not scraped) Reddit threads. Keep every card under
-- 90 characters to match the UI.

insert into posts (text, category, safety_flag, status, source) values
  ('He still texts his ex every Sunday, says it''s just checking in.', 'loyalty', false, 'approved', 'seed'),
  ('She reads my messages at 3am and says she wasn''t checking up on me.', 'trust', false, 'approved', 'seed'),
  ('He replies ''k'' to texts but posts a new story every hour.', 'trust', false, 'approved', 'seed'),
  ('My roommate borrows my stuff and ''forgets'' to ask, every week.', 'boundaries', false, 'approved', 'seed'),
  ('He split the bill on the first date, down to the exact rupee.', 'money', false, 'approved', 'seed'),
  ('My best friend only texts me when she needs a favor.', 'friendship', false, 'approved', 'seed'),
  ('My mom reads my texts, says it''s her right since she pays my bill.', 'family', false, 'approved', 'seed'),
  ('He never apologizes first, even when he''s clearly wrong.', 'honesty', false, 'approved', 'seed'),
  ('She still keeps every gift from her ex ''for sentimental reasons.''', 'loyalty', false, 'approved', 'seed'),
  ('My coworker takes credit for my ideas in every meeting.', 'work', false, 'approved', 'seed'),
  ('He wants the password to all my socials ''for trust.''', 'trust', false, 'approved', 'seed'),
  ('My in-laws want to pick where we live without asking us.', 'family', false, 'approved', 'seed'),
  ('She cancels plans last minute but gets upset if I make other ones.', 'friendship', false, 'approved', 'seed'),
  ('He ''forgot'' his wallet on the third date in a row.', 'money', false, 'approved', 'seed'),
  ('My partner tracks every rupee I spend and asks for receipts.', 'money', false, 'approved', 'seed'),
  ('He goes silent for days after every small disagreement.', 'honesty', false, 'approved', 'seed'),
  ('She talks about me to mutual friends, then acts normal to my face.', 'honesty', false, 'approved', 'seed'),
  ('My boss messages me ''urgent'' tasks at 11pm on weekends.', 'work', false, 'approved', 'seed'),
  ('He gets annoyed if I hang out with guy friends, has girl ''best friends'' himself.', 'boundaries', false, 'approved', 'seed'),
  ('My friend takes forever to pay me back and never brings it up first.', 'money', false, 'approved', 'seed'),
  ('She love-bombed me with gifts in week one, now barely replies.', 'loyalty', false, 'approved', 'seed'),
  ('He compares me to his mother''s cooking, constantly.', 'family', false, 'approved', 'seed'),
  ('My sister read my diary and still brings up what she found, years later.', 'family', false, 'approved', 'seed'),
  ('He wants to know my exact schedule every day, calls it ''just curious.''', 'boundaries', false, 'approved', 'seed'),
  ('She only compliments me when I''m doing worse than her.', 'friendship', false, 'approved', 'seed'),
  ('My date insisted on ordering for me without asking what I wanted.', 'boundaries', false, 'approved', 'seed'),
  ('He keeps a running tally of who paid for what, every single time.', 'money', false, 'approved', 'seed'),
  ('My roommate never buys groceries but eats everyone else''s food.', 'money', false, 'approved', 'seed'),
  ('She talks over me in every group conversation, every time.', 'friendship', false, 'approved', 'seed'),
  ('He says he''s ''not the jealous type'' then interrogates me about every text.', 'trust', false, 'approved', 'seed'),
  ('My parents want my salary slips every month, I''m 27 and independent.', 'family', false, 'approved', 'seed'),
  ('He ghosted for three weeks, came back like nothing happened.', 'honesty', false, 'approved', 'seed'),
  ('My friend group has a chat I got removed from, no explanation.', 'friendship', false, 'approved', 'seed'),
  ('She never says sorry first, waits for me to cave every time.', 'honesty', false, 'approved', 'seed'),
  ('He wants to split the ring cost but expects my family to fund the wedding.', 'money', false, 'approved', 'seed'),
  ('My manager takes credit for the team''s work in front of leadership.', 'work', false, 'approved', 'seed'),
  ('He checks who liked my posts and messages them if it''s a guy.', 'trust', false, 'approved', 'seed'),
  ('She ''jokes'' about my weight in front of our whole friend group.', 'friendship', false, 'approved', 'seed'),
  ('My partner wants a joint account before we''re even engaged.', 'money', false, 'approved', 'seed'),
  ('He calls me ''dramatic'' every time I bring up something that hurt me.', 'honesty', false, 'approved', 'seed'),
  ('My cousin only calls when she needs to borrow money.', 'family', false, 'approved', 'seed'),
  ('He wants to meet my parents after two weeks, already talks marriage.', 'loyalty', false, 'approved', 'seed'),
  ('She disappears for hours with no explanation, gets defensive if asked.', 'trust', false, 'approved', 'seed'),
  ('My coworker screenshots our DMs and shares them with the group.', 'work', false, 'approved', 'seed'),
  ('He says ''I''m not like your ex'' unprompted, multiple times a week.', 'honesty', false, 'approved', 'seed'),
  ('My friend only remembers my birthday when I remind her first.', 'friendship', false, 'approved', 'seed'),
  ('He gets quiet and cold for hours if I disagree with him in public.', 'honesty', false, 'approved', 'seed'),
  ('She asked me to co-sign a loan for her ''business idea.''', 'money', false, 'approved', 'seed'),
  ('My dad compares my grades to my cousin''s in front of every guest.', 'family', false, 'approved', 'seed'),
  ('He introduces me as his girlfriend but says ''no labels'' to my face.', 'loyalty', false, 'approved', 'seed'),
  ('My friend cancels on me but shows up for everyone else, every time.', 'friendship', false, 'approved', 'seed'),
  ('He wants me to send my location 24/7 ''for safety,'' won''t share his.', 'trust', true, 'approved', 'seed'),
  ('She shows up uninvited to places I mentioned, calls it a surprise.', 'boundaries', true, 'approved', 'seed'),
  ('He slowly stopped me from seeing my friends over a few months.', 'boundaries', true, 'approved', 'seed'),
  ('My partner reads through my phone every time I''m asleep.', 'trust', true, 'approved', 'seed'),
  ('He gets upset if I don''t reply within minutes, calls it ''caring.''', 'boundaries', true, 'approved', 'seed');
